// DropPilot content data (extracted from app.html). Loaded before the app script.

// Do not edit structure; content edits go through the normal content workflow.

var ALL_TIPS = [
  {e:"👋",t:"Greet with a smile",s:"First impressions decide your rating.",d:"Brief eye contact, say something simple — 'Hi, here's your order!' You don't need to be chatty. Just warm. Customers rate drivers who feel like real people much higher than ones who silently hand over the bag and walk away."},
  {e:"🔔",t:"Never knock on contactless orders",s:"A top cause of surprise 1-star ratings.",d:"If the customer chose Leave at Door, do NOT knock or ring. Set the food down neatly, photo it, mark delivered. They chose contactless for a reason. Respecting it shows you read their instructions — that earns 5 stars."},
  {e:"📸",t:"Photo every single delivery",s:"Your photo is your protection. No exceptions.",d:"Clear photo showing the food AND the door or house number together. Protects you if a customer ever claims they didn't get their order. Every time — good weather, bad weather, day or night."},
  {e:"💬",t:"Text when you're 3 minutes away",s:"Earns more 5-stars than almost any other habit.",d:"A quick 'Hi! About 3 minutes away with your order!' sets a professional tone before you arrive. Customers who know you're coming almost always rate higher. 10 seconds to send."},
  {e:"🌡️",t:"Handle food like it's your own meal",s:"How you carry the bag tells them everything.",d:"Hot food arrives hot. Bags don't get crushed. Drinks stay upright. These small details tell the customer whether you cared. Drivers who treat every order carefully get the best tips."},
  {e:"⚡",t:"Wrong door = dead account",s:"Speed means nothing at the wrong address.",d:"A delivery to the wrong address is one of the fastest ways to lose your account. Take 5 seconds to confirm before you get out of the car. That 5 seconds protects your entire standing on the platform."},
  {e:"🤐",t:"Never complain to the customer",s:"Your bad day isn't their problem.",d:"Long restaurant wait, bad traffic, app issues — the customer caused none of it and doesn't want to hear about it. Keep every interaction warm no matter how the shift is going. They're just happy the food arrived."},
  {e:"🎁",t:"Small extras = bigger tips",s:"Extra napkins. Level bag. Steady hand. It adds up.",d:"Extra napkins, keeping the bag level, drinks secured — none of these take more than a few seconds. But customers notice. They tip the drivers who clearly paid attention."},
  {e:"🚪",t:"Contactless means zero contact",s:"No knock. No ring. Clean drop.",d:"Leave at Door means exactly that. Set the food down neatly, photo it, confirm. A knock on a contactless order is one of the most common reasons good drivers get unexpected 1-stars."},
  {e:"📞",t:"When something goes wrong — text first",s:"One proactive message prevents a bad review.",d:"Gate code missing? Can't find the unit? Nobody answering? Text before you call or leave. A calm simple text gives the customer a chance to help — and it shows you tried. That effort almost always protects your rating."},
];

var LEARN_CATS = [
  {
    e:"🧠", t:"Reading People", sub:"Simple psychology you can use right now", free:true,
    secs:[
      {h:"Handoff and Goodbye", body:"People don't remember the whole delivery. They remember two moments — the handoff and the goodbye. Nail those two and they rate you 5 stars even after a long wait. Everything else is noise. Before every delivery, remind yourself: handoff, goodbye. Those are the two moments that decide your rating.", tip:"Two moments decide everything. Handoff. Goodbye."},
      {h:"Use Their Name Once", body:"Your app shows the customer's first name. Most drivers ignore it. Big mistake — hearing your own name flips the moment from 'handled' to 'seen.' Use it exactly once: 'Here you go, Marcus — enjoy your meal!' Once feels warm. Twice feels weird. Three times feels creepy.", tip:"Once. Not twice. Never three times."},
      {h:"Read, Match, Mirror", body:"Some customers text casually: 'yo food almost here??' Others are formal: 'Could you provide an estimated arrival time?' Most drivers send the same message to everyone. Mirror their style instead. Casual → casual. Formal → polite. They feel understood without knowing why.", tip:"Read their text. Match their tone. Mirror it back."},
    ]
  },
  {
    e:"🚪", t:"At The Door", sub:"Small habits that change how customers see you", free:true,
    secs:[
      {h:"Step Aside, Step Down", body:"Don't stand dead center — it feels aggressive, like you're blocking them. Stand slightly to the side. Hold the bag out. On steps, stand one step below the top. Being slightly lower than the customer reads as friendly, not imposing. The position itself says 'I'm here to give you something,' not 'I'm in your way.'", tip:"Step aside. Step down. Hold the bag out."},
      {h:"Two Hands, Chest Height", body:"One hand swinging looks like garbage. Two hands at chest height looks like care. Customers feel the difference without knowing why. Rule: any order with drinks → two hands, always level. The 5 extra seconds earns the tip.", tip:"Two hands. Chest height. Always."},
      {h:"Pause Before You Go", body:"After you hand over the bag and say goodbye, pause half a second. One brief glance. Then leave. That tiny pause turns a drop-off into a real human moment. Drivers who pause are described as 'really nice.' Drivers who don't are described as 'rushed' — even at identical times.", tip:"Count one in your head. Then go."},
    ]
  },
  {
    e:"🔥", t:"Handling Difficult Situations", sub:"What to say when things go wrong", free:false,
    secs:[
      {h:"Feel. Felt. Found.", body:"The 3-step formula for any frustrated customer.\n1. 'I understand how you feel.' — you heard them.\n2. 'A lot of customers feel the same way.' — their frustration is normal.\n3. 'What I've found is…' — give them the next step.\nExample for a late delivery: 'I completely understand how you feel — waiting is frustrating. A lot of customers feel the same after a long wait. What I've found is a quick message to support usually fixes this fast.' You're not admitting fault. You're acknowledging feeling.", tip:"Feel. Felt. Found. Three steps. Works every time."},
      {h:"Out-Calm, Don't Out-Argue", body:"Anger speeds you up. Resist it. Slow down, lower your voice, breathe. Calm is contagious — just like anger is. You can't out-argue an angry customer. But you can out-calm them. Don't interrupt. Don't list reasons it isn't your fault. Most people follow your lead within 30 seconds.", tip:"Defensive? Speak slower and quieter — not faster and louder."},
      {h:"Redirect, Don't Argue", body:"Sometimes a customer insists something happened that you know didn't. You can't tell them they're wrong — that's a fight you can't win. Redirect to support instead. 'I'm really sorry to hear that — reach out to [platform] support directly. They deal with this all the time and they'll make it right fast.' You're not admitting fault. You're not arguing. You're pointing them at the fastest fix.", tip:"End the call calm with a path forward. Don't try to win the argument."},
      {h:"Know When to Walk Away",body:"De-escalation has a limit. If a customer is filming you to provoke a reaction, shouting threats, or getting physically close — stop trying to win the interaction and leave. Say one calm line: 'I'm going to head out now.' Don't argue, don't explain, don't perform for the camera. Walk to your car, lock the doors, drive to a safe spot. Then document: time, address, exactly what was said or done, and any dashcam footage. File an in-app safety report the same day. Your rating can recover. Your safety can't.",tip:"Filming, threats, or closing distance — leave. Document. Report. Same day."},
    ]
  },
  {
    e:"💰", t:"The Science of Tips", sub:"Why people tip — and how to make it happen", free:false,
    secs:[
      {h:"Two Hands = More Tips", body:"Drivers consistently report that brief moments of real physical exchange increase tips. You can't manufacture extra contact at someone's door — but a two-handed bag presentation is the delivery version. Two hands, chest height, facing them. It creates an exchange instead of a drop-off. Customers feel the difference without knowing why.", tip:"Two hands every time. It's not the bag — it's the moment."},
      {h:"Empathy, Not Complaint", body:"Experienced drivers say briefly mentioning weather — empathetic, not whiny — increases tips. 'Stayed moving fast for you out there — cold one tonight!' Empathy earns tips. Complaints ask for sympathy. Different things. The key: one warm sentence, no whining.", tip:"One sentence. Warm, not whiny."},
      {h:"The Mention Is the Gift", body:"Unexpected gifts trigger reciprocity — people feel an urge to give back. Extra napkins, drinks held perfectly upright, a warm confirmation text — all gifts. The catch: they only count if you mention them out loud. 'Grabbed a few extra napkins in case you need them!' Unsaid gifts are invisible. Said gifts pay tips.", tip:"The mention is the gift. Say it out loud."},
      {h:"Confirm the Pre-Tip Promise", body:"Many platforms let customers tip before delivery. That tip is a bet on you. Your job is to confirm the bet. A warm handoff and a clean photo almost never get a tip reduced. A careless drop-off sometimes does. Every delivery either confirms or breaks the promise the customer made when they tipped.", tip:"Every delivery confirms or breaks the pre-tip promise."},
      {h:"Tip Baiting Is Real — Don't Chase It",body:"Tip baiting is when a customer posts a big tip to get their order picked up fast, then lowers or removes it after delivery. Most major apps — DoorDash, Uber Eats, Instacart — let customers change a tip after the fact, and there's nothing you can do to stop it. The worst response is messaging the customer about it: it reads as threatening, it can trigger a complaint, and it has never once restored a tip. Screenshot the original offer for your own records, note the pattern, and move on. If one customer does it repeatedly, report the pattern to support — that's the only channel that can act on it.",tip:"Screenshot it. Note it. Move on. Never message the customer about a tip."},
    ]
  },
  {
    e:"📋", t:"Recovery Scripts", sub:"Exactly what to say when there's a problem", free:false,
    secs:[
      {h:"Cold Food → Redirect to Support", body:"Cold food is almost always the restaurant's fault — but saying so sounds like an excuse. Don't. Instead: 'I'm really sorry about that. I'd contact [platform] support — they take temperature issues seriously and fix it fast.' You're not taking blame. You're pointing at the fix. That's what they actually want.", tip:"Never blame the restaurant out loud. Redirect to support every time."},
      {h:"Never Claim You Checked the Bag", body:"'I checked the bag and everything was in there' is an unwinnable argument. Don't say it — even if you believe it. Instead: 'I'm so sorry — I picked up the sealed bag from the restaurant. Fastest fix is [platform] support.' Let the platform handle it. That's what they're there for. Your rating stays clean.", tip:"Never claim you checked. Always redirect to support."},
      {h:"Own It. One Sentence. Stop.", body:"If the mistake was yours — wrong address, took too long, dropped something — own it fully and briefly. 'That was completely my fault and I'm sorry.' Then stop. No 'but traffic.' No 'app was glitching.' Customers rate higher after a mistake handled with full ownership than after a perfect delivery. Own it. They respect you.", tip:"Own it. One sentence. Stop. No excuses."},
    ]
  },
  {
    e:"🗺️", t:"Know Your Delivery", sub:"Different situations need different approaches", free:false,
    secs:[
      {h:"Speed-and-Warmth or Care-and-Comms", body:"Restaurant orders → speed and warmth. Hot food, fast handoff, brief greeting. Grocery orders → care and communication. Customers care about produce quality, careful handling, messages about anything out of stock. Don't run grocery like restaurant. Don't run restaurant like grocery.", tip:"Restaurant: fast and warm. Grocery: thorough and chatty."},
      {h:"Apartments: Text First, Always", body:"Houses are easy: walk to the door, knock once, step back. Apartments are different. Always text first — 'Hi! At the main entrance — could you buzz me in?' The customer has no idea you're outside. Quick communication beats slow silent every time.", tip:"Apartment rule: text first, always. Don't assume — communicate."},
      {h:"Read the Clock Like an Instruction", body:"Lunch (11–2): work break. Be fast and brief. Dinner (5–9): warmth wins — 'enjoy your meal' earns more here than anywhere. Late night (10–2): quiet, no loud knocks, clean drop. Morning (5–10): upbeat — bar is low, friendliness stands out. The clock tells you exactly how to adjust before you arrive.", tip:"Time of day = how to act. Read the clock like instructions."},
    ]
  },
  {
    e:"🏆", t:"Staying Sharp", sub:"How to keep earning more over the long run", free:true,
    secs:[
      {h:"Every Door = New Customer", body:"In a regular job, one bad day doesn't end your career. In gig delivery, every order is rated alone — by someone who knows nothing about your last delivery. That's good news: a bad delivery doesn't have to affect the next one. Unless you carry the frustration with you. The skill that pays best isn't driving. It's starting fresh every single time.", tip:"This customer has never met you. Don't bring frustration to their door."},
      {h:"Breathe. Reset. Pick One.", body:"After a rough delivery, take 60 seconds before the next.\n1. Breathe — it's over. You can't change it.\n2. Remember the next customer is a completely different person.\n3. Pick one small thing to do well — just one.\nThat's the reset. Drivers who do this are more consistent, rate higher, and earn more over time.", tip:"Breathe. Reset. Pick one thing for the next delivery."},
      {h:"Track Trends, Not Single Ratings", body:"Burnout sneaks up. Watch for: stopping the proactive texts, drop-and-go handoffs, anger at low ratings, no eye contact at the door. The fix usually isn't quitting — it's adjusting. Fewer hours. Different zone. Track your weekly tip average instead of every single rating. Trends motivate. Single data points just hurt.", tip:"Track weekly tip average. Not individual ratings."},
    ]
  },
  {
    e:"🍔", t:"At The Restaurant", sub:"Handling issues at pickup that protect your rating", free:false,
    secs:[
      {h:"Photo the Receipt", body:"The moment you pick up a sealed bag, you own it. Verify before you take it.\n1. Order number matches your app.\n2. Count items if the bag is open.\n3. Scan for drinks — the #1 missing item.\n4. Photo the order ticket or receipt.\nThe receipt photo is your proof of what you picked up. 30 seconds. Eliminates a whole category of false complaints.", tip:"Photo the receipt. It's your proof."},
      {h:"Missing at Restaurant Stays at Restaurant", body:"Something missing while you're still at the restaurant? Stop. Don't leave. 'This order is missing [item] — can we add it before I take it?' If they're out of stock, ask what they substituted and confirm the customer approved it. At the door, tell the customer plainly: 'Restaurant was out of [item], they substituted [X].' Then it's their call, not yours. Never leave incomplete and hope.", tip:"Missing at the restaurant stays at the restaurant."},
      {h:"Wait Quietly. Communicate Loudly.", body:"Order isn't ready? Don't stand there frustrated.\n1. Ask staff: 'What time should I check back?'\n2. Step aside. Hovering slows them down.\n3. Message the customer: 'Still waiting on prep — should be ready in about [X] min.'\n15 seconds saves your rating. A customer with no info imagines the worst. A customer with info stays calm. Past 10 min late? Re-message and screenshot the time for proof.", tip:"Step aside. Message the customer. Screenshot the wait."},
      {h:"Damage at Pickup Stays at Pickup", body:"Inspect the bag before you leave. Drinks: any wetness? Fragile items: any crushing? Damage spotted? Don't take it. 'This one looks damaged — can we get a replacement?' Don't accept a discount or fix-it-later. If you don't catch it until the door, photo it, show the customer, then contact support. Customers remember the driver who caught the problem and fixed it.", tip:"Damage at pickup stays at pickup. Never transport hoping they won't notice."},
    ]
  },
];

var MSG_CATS = [
  {e:"📲",t:"What to Say When You Arrive",sub:"Texts that get 5-star ratings",secs:[
    {h:"Standard arrival",msg:"Hey! Pulling up now with your order from [restaurant]. I'll leave it at your door. Enjoy! 😊",w:"Sets expectations before they open the app. Customers often rate you before they even see the food.",hint:"Replace [restaurant] with the actual restaurant name — e.g. 'McDonald's' or 'Chipotle'."},
    {h:"A few minutes away",msg:"Hi! Just a heads up — about 3-4 minutes away with your food. See you soon!",w:"Advance notice means they meet you at the door or are ready when you arrive. Cuts your wait time too."},
    {h:"Apartment building",msg:"Hi! I'm at the main entrance with your order. Could you buzz me in or meet me at the lobby? Thanks!",w:"Always text before calling for apartments. Most people respond in under 30 seconds when their food is outside."},
    {h:"Leave at door confirmation",msg:"Your order has been left at your door. Enjoy your meal! 🍕",w:"A quick confirmation nearly eliminates false non-delivery complaints."},
    {h:"Office or business",msg:"Hi! Downstairs at [building] with your order. Happy to leave it at the front desk or you can meet me!",w:"Offering options signals professionalism and saves you a wasted trip.",hint:"Replace [building] with the company or building name shown in the app."},
  ]},
  {e:"⏰",t:"When You Are Running Late",sub:"How to turn a bad situation into a 5-star",secs:[
    {h:"Restaurant taking forever",msg:"Hey! Your order is still being prepared at the restaurant. I'm here and will head your way as soon as it's ready. Thanks for your patience!",w:"Customers who hear nothing assume you forgot them. One text flips that completely. 'Thanks for your patience' credits the customer — 'sorry for the wait' puts you in a guilty position for something that isn't your fault."},
    {h:"Stuck in traffic",msg:"Hi! Running a little behind due to traffic. On my way and will be there as soon as I can — thanks for your patience!",w:"Never blame the app or restaurant. Own it briefly and stay positive."},
    {h:"Significantly late",msg:"Hi! Really sorry for the delay tonight. Dealing with [traffic / long restaurant wait] and I'll be there in about [X] minutes. I truly appreciate your patience.",w:"Bigger delays need a bigger acknowledgment. Be direct, give a real ETA.",hint:"Replace [traffic / long restaurant wait] with what's actually happening, and [X] with your real estimated minutes."},
    {h:"Follow up after a late delivery",msg:"Just dropped off your order — really sorry for the wait tonight. Hope everything still tastes great! Have a good evening.",w:"Almost no drivers do this. It often turns a 3-star into a 5-star."},
  ]},
  {e:"🚨",t:"When Something Goes Wrong",sub:"Scripts that protect your rating",secs:[
    {h:"Cannot find the address",msg:"Hi! Having a little trouble locating you. I'm near [landmark]. Could you help with directions or a gate code?",w:"Always text before calling. Give them something specific to work with.",hint:"Replace [landmark] with something you can see nearby — a store name, street sign, or building."},
    {h:"Need a gate code",msg:"Hi! At the gate but need a code to get in. Could you send it over? Right here!",w:"People respond in seconds when their food is right outside."},
    {h:"No one answers the door",msg:"Hi! At your door and knocked. I'll wait a couple minutes — if I don't hear back I may need to leave it at the door. Just want to make sure you get it!",w:"Documents your attempt and gives them a chance to respond."},
    {h:"Safe drop-off with photo",msg:"Your order has been left at your door. Took a photo as confirmation. Enjoy!",w:"Mentioning the photo casually shields you from false complaints."},
    {h:"Large apartment complex",msg:"Hi! I'm in the [building/complex name] parking lot but having trouble finding your unit. Could you help — which building number, entrance, or stairwell? Almost there!",w:"Asking for a specific landmark gets you a useful answer fast.",hint:"Replace [building/complex name] with the apartment complex name from the delivery address."},
  ]},
  {e:"⭐",t:"How to Get Better Tips and Ratings",sub:"What to say — and what never to say",secs:[
    {h:"Natural sign-off that earns tips",msg:"Enjoy your meal! If anything ever comes up feel free to reach out through the app. Have a great night! 😊",w:"Positions you as someone who cares — without ever asking for anything."},
    {h:"When you went above and beyond",msg:"Thanks for the order! Made sure to keep everything upright and warm on the way. Hope you enjoy every bite!",w:"Pointing out your care makes them look in the bag with appreciation, not suspicion."},
    {h:"When you added something extra",msg:"Hi! The bag was light on napkins so I grabbed a few extras. Everything else looks good — enjoy!",w:"If you don't mention it they might not notice. If you do, it's memorable."},
    {h:"What you should NEVER say",caution:true,msg:"Please leave me 5 stars! / I really need a good rating this week. / Could you add a tip? / This order was really far.",w:"Asking for ratings or tips is against platform rules and makes customers deeply uncomfortable. It almost always results in a worse rating, not a better one."},
  ]},
  {e:"🏢",t:"Tricky Delivery Situations",sub:"Word-for-word scripts for the hard ones",secs:[
    {h:"Hotel delivery",msg:"Hi! In the lobby of [hotel] with your order. The front desk can't accept deliveries — would you be able to come down? Happy to wait!",w:"Always announce from the lobby, not the room floor.",hint:"Replace [hotel] with the hotel's actual name."},
    {h:"Gated community, no code",msg:"Hi! At the gate but did not get a code with the order. Could you send it or buzz me in? Right here!",w:"Don't wait. Text immediately. Every minute at the gate is wasted."},
    {h:"Customer seems upset at the door",msg:"I understand — got here as fast as I could. I hope the rest of your evening gets better from here!",w:"Empathy, not apology. You don't know what 'that' is — it may have nothing to do with you. 'I understand' acknowledges their feeling without admitting fault. Short, calm, warm. Wish them well and leave."},
  ]},
  {e:"🚗",t:"Rideshare — Ride Messages",sub:"For pickups, no-shows, and tricky passenger situations (Lyft & Uber)",secs:[
    {h:"On my way to your pickup",msg:"Hey! On my way — about 2-3 minutes out. I'll be in a [car color and model]. See you shortly!",w:"Passengers who know what car to look for find you faster, cutting wait time and reducing cancellations before you even arrive.",hint:"Replace [car color and model] with your car's description — e.g. 'silver Honda Accord' or 'white Toyota Camry'."},
    {h:"At pickup — passenger not visible",msg:"Hi! I'm at your pickup location. I'm in a [car color and model] — let me know if you need me to pull up a bit!",w:"Send this instead of waiting silently or cancelling early. Most passengers respond in under a minute when they know you're there.",hint:"Replace [car color and model] with your car's description — e.g. 'silver Honda Accord'."},
    {h:"Slight delay on the way to pickup",msg:"Hey! Running about [X] minutes late — slight [traffic / detour]. Still on my way and almost there!",w:"One honest heads-up almost always prevents a cancellation. Passengers who know you're coming rarely leave.",hint:"Replace [X] with your real estimated delay in minutes, and [traffic / detour] with the actual reason."},
    {h:"Passenger left something in your car",msg:"Hi! It looks like you may have left [item] in my car. I've reported it through the [Lyft / Uber] app — you can claim it through your ride history under Lost Items. Hope you get it back!",w:"Always report lost items through the app's official lost and found — never arrange returns directly outside the app. This protects both you and the passenger.",hint:"Replace [item] with what they left — e.g. 'your phone' or 'a backpack'. Use Lyft or Uber for [Lyft / Uber]."},
    {h:"Passenger seems upset during the ride",msg:"I'm sorry you're having a rough time. Let me get you there as smoothly as I can.",w:"Short, calm, genuine. Don't ask what's wrong, don't over-explain, don't apologize for things you didn't do. Just acknowledge and refocus on the drive. Most passengers will settle down within 60 seconds."},
  ]},
  {e:"🔥",t:"De-Escalation Scripts",sub:"Word-for-word responses when a situation gets hard",secs:[
    {h:"Customer threatening a bad rating",msg:"I'm sorry to hear you're not happy. I genuinely did my best on this delivery. If there's an issue with the order itself, support can make it right — they're the fastest path to a resolution.",w:"Doesn't argue, doesn't plead. Acknowledges your effort, redirects to the channel that can actually fix it. Keeps you out of a back-and-forth that won't end well."},
    {h:"Angry customer at the door",msg:"I hear you — I'm sorry for the wait. I got here as quickly as I could. I hope the food makes up for it. Have a good night.",w:"Four sentences. Acknowledge, brief context, warmth, exit. You're not debating the wait time — you're ending the interaction. Short and done is better than long and right."},
    {h:"Customer insisting the order is wrong (sealed bag)",msg:"I picked up the sealed bag directly from the restaurant — everything was packed by them. For a missing or wrong item, support can issue a credit or replacement quickly. I'd go through the app — they usually sort it out fast.",w:"Factual and redirect. You're not responsible for what the restaurant packed in a sealed bag. This frames things correctly without sounding defensive."},
    {h:"Passenger upset about the route",msg:"I hear you — I'll keep that in mind. Let me get you there as smoothly as I can from here.",w:"Acknowledge once, pivot forward. You're not agreeing you were wrong. You're not explaining yourself. One acknowledgment and one forward-looking sentence ends it."},
    {h:"Customer says you left without them knowing",msg:"Hi — I arrived at [address] at [time] and waited [X] minutes. I sent a message through the app before completing the delivery. I'm sorry we missed each other — support should be able to review the delivery record.",w:"Factual, documented, no apology for completing correctly. You have a timestamp, a message record, and a photo. State the facts calmly and point them to support."},
    {h:"When you need to end a ride early for safety",msg:"I'm going to need to end this trip here. I hope you get where you're going safely.",w:"Short, calm, final. You don't owe an explanation. If you feel unsafe, end it — that's always the right call. Report through the app immediately after with specific details of what happened."},
  ]},
  {e:"🛡️",t:"Protecting Yourself at the Door",sub:"ID checks, boundaries, and damage — handled right",secs:[
    {h:"Alcohol delivery — ID check",msg:"Hi! I've got an alcohol delivery here — I'll just need to see your ID at the door to complete it. Thanks!",w:"Frames it as a platform requirement, not your personal judgment. Nobody argues with 'the app requires it.'",hint:"Check the birthdate and that the photo matches before handing anything over — never guess."},
    {h:"Customer asks for something extra",msg:"I totally get it — but I'm not able to do that one. The app only covers the delivery itself. Happy to leave everything right here at the door for you!",w:"Blames the app, not you. 'Not able to' is softer than 'won't,' and offering the door drop keeps it warm.",hint:"Use for any off-app request — carrying items upstairs, extra stops, buying something additional."},
    {h:"Food spilled or damaged in transit",msg:"Quick heads up — [item] shifted a bit on the way over. Everything else is secure. The fastest fix is a quick note to support in the app — they handle this all the time.",w:"Honesty before they open the bag beats discovery after. Redirecting to support protects your rating and gets them a credit faster than you ever could.",hint:"Replace [item] with what spilled — e.g. 'your drink' or 'the soup container'."},
    {h:"Batched order — customer confusion",msg:"Quick heads up — I have two deliveries on this trip, so yours may arrive a few minutes after your neighbor's. Everything's on its way!",w:"Preempts the 'where's mine' text completely. Customers who expect a gap don't punish you for it.",hint:"Send as soon as you see the batch has two nearby stops."},
  ]},
];

var PLATFORMS_DEFEND = [
  {id:"doordash",  label:"DoorDash",  color:"#FF3008", e:"🔴"},
  {id:"ubereats",  label:"Uber Eats", color:"#06C167", e:"🟢"},
  {id:"spark",     label:"Spark",     color:"#0071CE", e:"🔵"},
  {id:"instacart", label:"Instacart", color:"#43B02A", e:"🟩"},
  {id:"lyft",      label:"Lyft",      color:"#FF00BF", e:"🚙"},
  {id:"amazonflex", label:"Flex",      color:"#FF9900", e:"📦"},
  {id:"uber",      label:"Uber",      color:"#1D1D1D", e:"🚗"},
  {id:"gopuff",    label:"GoPuff",    color:"#4338CA", e:"🟣"},
];

var PLATFORM_HABITS = {
  doordash:[
    {e:"📸",t:"Photo every drop-off",why:"Your photo is your #1 protection. DoorDash support checks it against your GPS. A clear photo showing the food at the door with the address visible wins almost every false non-delivery case. Without it, you have no case.",urgent:true},
    {e:"💬",t:"Message in-app on every order",why:"Your in-app message history is timestamped and visible to Dasher support. When a customer claims you never communicated, your thread proves otherwise. One text per delivery protects you completely.",urgent:true},
    {e:"📍",t:"GPS on the entire shift",why:"DoorDash logs your location throughout the delivery. If a customer reports non-delivery, support pulls your GPS track to confirm you were at their address. Without GPS, your word means nothing.",urgent:true},
    {e:"🖼️",t:"Screenshot the delivery confirmation",why:"After the app shows delivery confirmed, screenshot it before moving on. This is the platform's own timestamped record that the order was completed — separate from your photo, and equally important in a dispute."},
    {e:"💎",t:"Screenshot the offer screen on high-pay orders",why:"When promised pay and final pay differ, the screenshot is your proof. Save it before you accept — once the order is complete, the original offer screen is gone."},
    {e:"📋",t:"Note the order number on any problem delivery",why:"If a restaurant runs late, a customer seems upset, or anything feels off — quickly note the DoorDash order number. This is what agents use to pull your record. It makes any appeal far stronger."},
  ],
  ubereats:[
    {e:"📸",t:"Photo every drop-off",why:"Uber Eats requires a photo for contactless deliveries. That photo is timestamped, geotagged, and stored in Uber's system. In any dispute, support pulls it immediately. If you didn't take one, you have no evidence.",urgent:true},
    {e:"💬",t:"Message in-app only — never SMS",why:"Uber support can only see your in-app message history, not regular texts. Always message through the Uber Eats app so every communication is logged. In-app messages are your proof if a customer claims you ignored them.",urgent:true},
    {e:"📍",t:"GPS on the entire shift",why:"Uber's dispute system relies on GPS trip data more than any other platform. Agents check your track in every delivery complaint review. If GPS was off, they can't verify and they typically side with the customer.",urgent:true},
    {e:"🆔",t:"Screenshot your Trip ID on problem deliveries",why:"Uber identifies every delivery by a Trip ID. In any support appeal, you must include it — without the Trip ID, agents can't find your record. Screenshot the trip summary screen after anything that felt off."},
    {e:"⭐",t:"Your rating decides which trips you see",why:"Uber shows higher-paying trips to higher-rated drivers. Below 4.7 on Uber Eats starts to reduce your trip quality. Uber's policy allows removal of ratings caused by restaurant errors or factors outside your control — request it."},
    {e:"🔄",t:"Document long restaurant waits with a message",why:"Wait more than 10 minutes at a restaurant? Send the customer an in-app note about the delay. Creates a timestamped record that the wait was the restaurant's fault, not yours — which matters if they rate you low for timing."},
  ],
  spark:[
    {e:"📸",t:"Photo every drop-off",why:"Walmart Spark requires a photo on every order. It's your proof of delivery and your protection against false claims. Clear photo showing bags at the door with the house number visible. Without it, support sides with the customer.",urgent:true},
    {e:"📦",t:"Verify the full order at the store",why:"Spark drivers are responsible for picking items. If something is missing, customers can complain against you. Before leaving the store: verify all items, note anything unavailable in the app, photograph the cart on large orders.",urgent:true},
    {e:"💬",t:"Message in-app about every substitution",why:"When an item is unavailable and you substitute it, message the customer through the Spark app before you leave the store. This shows you followed the substitution process. Agents check your message history in every dispute.",urgent:true},
    {e:"📍",t:"GPS on the entire shift",why:"Spark uses GPS to verify delivery location and timing. If GPS confirms you were at the address, that's your strongest evidence. If it was off, you have no way to prove the delivery happened."},
    {e:"🧾",t:"Screenshot the delivery summary",why:"After completing an order, the Spark app shows a summary of what was delivered, including substitutions and unavailable items. Screenshot every time. If a customer claims items were missing, this is the system's own record."},
    {e:"⭐",t:"On-time rating is tracked separately",why:"Spark tracks your on-time delivery rate separately from your customer rating. Both affect access to better batches. Store delay made you late? Message the customer and note the wait — that gives grounds to dispute a late mark."},
  ],
  instacart:[
    {e:"📸",t:"Photo every drop-off",why:"Instacart requires a delivery photo and uses it in every non-delivery dispute. Must show items at the door with the address or house number visible. Support looks at this first. Without it, you cannot win any non-delivery case.",urgent:true},
    {e:"🛒",t:"Scan every item at the store",why:"Instacart tracks which items you scanned. If a customer says an item was missing and you scanned it, that scan record is your proof. If you didn't scan it, the system has no record you had it. Every item, every time.",urgent:true},
    {e:"💬",t:"Message in-app about every replacement",why:"When an item is out of stock and you replace it, message the customer through the Instacart app before checkout. If they dispute the replacement later, your message shows you followed the right process.",urgent:true},
    {e:"📋",t:"Note your Batch ID on any problem order",why:"Instacart support identifies orders by Batch ID. For any delivery where something goes wrong, note or screenshot the Batch ID immediately. You cannot file an effective appeal without it."},
    {e:"⭐",t:"4.7 is the rating to protect",why:"Shoppers below 4.7 see fewer and lower-paying batches. Some high-paying batches are only available above 4.8. Rating removal is possible for complaints caused by out-of-stock items, store errors, or app issues — but you have to request it."},
    {e:"🔄",t:"Document difficult customers before they complain",why:"Customer rude or making unreasonable demands? Note it in the Instacart app feedback right away. Creates a record before any dispute is filed. Signals to support that the customer has a history if they later file a false complaint."},
  ],
  amazonflex:[
    {e:"📸",t:"Photo every drop-off",why:"Flex relies heavily on delivery photos. Clear, well-lit photo showing package(s) in their final location (porch, mailbox, etc.). This is your #1 protection against 'never received' complaints.",urgent:true},
    {e:"📍",t:"GPS on the entire shift",why:"The platform logs your GPS route. In any dispute, support checks your track against the delivery address and timestamp. GPS off = no proof.",urgent:true},
    {e:"🔢",t:"Scan one address at a time on multi-package stops",why:"This forces the app to prompt for a photo at every stop. Skipping this is a common reason drivers get dinged for missing packages.",urgent:true},
    {e:"🖼️",t:"Screenshot the delivery confirmation",why:"After marking delivered, screenshot the confirmation screen immediately. Shows the exact time and TBA/package IDs — your proof of completion if disputed."},
    {e:"🔄",t:"Return undeliverables with correct reason code",why:"Always use the app's undeliverable reason code at the location if you can't deliver. Bring them back to the station same day or by 10am next day."},
    {e:"📋",t:"Note Block ID and TBA on problem deliveries",why:"Support identifies your block by Block ID and individual packages by TBA. Screenshot or note them immediately if anything feels off — you can't appeal without them."},
  ],
  lyft:[
    {e:"🪪",t:"Confirm the passenger's name first",why:"Your #1 safety protection and Lyft's official policy. Before unlocking, ask 'What's your name?' and wait for them to tell you. Never say the name first — if someone gets in the wrong car, you could be held responsible.",urgent:true},
    {e:"📋",t:"Screenshot Trip ID if anything feels off",why:"Lyft uses Trip IDs to pull your record in any dispute. If a passenger is difficult or complains, the Trip ID is how support finds your ride. Screenshot the trip summary after any uncomfortable ride — before the app resets.",urgent:true},
    {e:"🔇",t:"Let the passenger set the tone",why:"About 60% of Lyft passengers prefer quiet rides. Never start talking the moment they get in. Give them 15–20 seconds. They speak first → follow their lead. They stay quiet → stay quiet. Forced conversation is a top cause of low ratings.",urgent:true},
    {e:"🚗",t:"Clean car. Charger ready.",why:"Cleanliness is the most-cited factor in passenger ratings. No strong odors, tidy interior, phone charger available (both iPhone and Android). Passengers mention the charger in positive reviews more than almost any other detail."},
    {e:"⭐",t:"Rate the passenger 5 stars immediately",why:"Passengers who see you rated them 5 stars are significantly more likely to rate you 5 stars back. Rate before they've had a chance to. Triggers a reciprocity response. Drivers who rate first consistently see higher overall ratings."},
    {e:"🎵",t:"Ask before playing music — keep volume low",why:"Never assume a passenger wants your playlist. 'Mind if I put something on?' shows respect and almost always gets a yes. Loud music, heavy bass, or aggressive lyrics are top-five causes of 3-star ratings. When in doubt: silence."},
  ],
  uber:[
    {e:"🪪",t:"Confirm the passenger's name first",why:"Ask 'What's your name?' before unlocking — never say the name first. If someone gets in the wrong car you could be held responsible. Uber's official policy and your legal protection on every ride.",urgent:true},
    {e:"📋",t:"Screenshot Trip ID if anything feels off",why:"Uber uses Trip IDs to find your record in any dispute. Difficult passenger or complaint? The Trip ID is how support locates the ride. Screenshot the trip summary immediately after — before the app resets.",urgent:true},
    {e:"🔇",t:"Let the passenger set the tone",why:"Never start talking the moment they get in. Give them 15–20 seconds. They speak first → follow their lead. They stay quiet → stay quiet and professional. Forced conversation on a passenger who wants silence is a common cause of low ratings.",urgent:true},
    {e:"🚗",t:"Clean car. Charger ready.",why:"Car cleanliness is the most-cited factor in passenger ratings. No strong odors, tidy interior, phone charger ready (iPhone and Android). Restock chargers regularly — passengers mention them more than almost any other detail."},
    {e:"⭐",t:"Rate the passenger 5 stars immediately",why:"Passengers who see you rated them 5 stars are significantly more likely to rate you 5 stars back. Rate them before they've had time to rate you. Drivers who rate first consistently see higher overall ratings."},
    {e:"📷",t:"Keep a dashcam active",why:"Uber's in-car video recording is available in all 50 states. A dashcam creates a record for any disputed complaint. Won't prevent false complaints, but it gives you documented evidence — and passengers behave differently when they see one."},
  ],
  gopuff:[
    {e:"📸",t:"Photo every drop-off",why:"Your photo is your primary protection against false non-delivery complaints. Clear photo showing items and the door number or house address. GoPuff's support team reviews these the same way all delivery platforms do.",urgent:true},
    {e:"📦",t:"Verify your order count at the facility",why:"GoPuff orders are pre-packed, but errors happen. Before leaving the facility, confirm the bag or item count matches the app. Leaving with a wrong or incomplete order creates a complaint you'll be responsible for.",urgent:true},
    {e:"📍",t:"GPS on the entire shift",why:"GoPuff uses GPS to confirm your delivery location and timing. It's your primary documentation that you were at the address and when."},
    {e:"💬",t:"Message in-app on any issue",why:"Gate code needed, can't find the address, customer not responding — always message in-app first. Documented in-app messages show you made a good-faith effort, which protects you in any dispute."},
    {e:"🏃",t:"Keep deliveries moving",why:"GoPuff's core promise is quick delivery. Consistently slow times affect your standing. Only accept runs you can realistically complete within the expected window."},
  ],
};

var PLATFORM_APPEALS = {
  doordash:[
    {e:"🚫",t:"False Non-Delivery Complaint",urgency:"HIGH — Can trigger deactivation",color:"#F43F5E",secs:[
      {h:"Standard non-delivery dispute",timing:"File within 24 hours — support reviews complaints in daily batches",msg:"Hello Dasher Support,\n\nI am writing to dispute a false non-delivery complaint on Dasher order #[ORDER ID] from [DATE].\n\nThis delivery was completed successfully. My documentation:\n- Delivery photo showing the order placed at [ADDRESS] with the door visible\n- GPS data confirming my location at [ADDRESS] at [TIME]\n- App delivery confirmation timestamp\n\nThe customer's claim is inaccurate. I am requesting:\n1. This complaint be reviewed against my delivery photo and GPS data\n2. Any negative impact on my completion rate or Dasher standing be reversed\n3. The customer's account be reviewed if this is part of a pattern\n\nThank you.",w:"'Dasher order #' is the exact term DoorDash support uses to pull your record. List each piece of evidence as a separate bullet — agents check each one individually."},
      {h:"Same address filing multiple complaints",timing:"File as soon as the second complaint appears — pattern reports get escalation treatment",msg:"Hello Dasher Support,\n\nI am writing about a pattern of false complaints I believe is coming from the same location.\n\nComplaints from [ADDRESS]:\n- Order #[ORDER ID 1] on [DATE 1] — I have delivery photo proof\n- Order #[ORDER ID 2] on [DATE 2] — I have delivery photo proof\n\nI believe this customer is repeatedly filing false non-delivery complaints to receive refunds. I am asking for:\n1. A review of all complaints from this address against my delivery evidence\n2. This address to be flagged in DoorDash's system if a pattern is confirmed\n3. All negative effects on my account to be reversed\n\nThank you.",w:"The phrase 'pattern of false complaints' moves your ticket from an individual review to a fraud investigation — handled differently and more seriously."},
    ]},
    {e:"⭐",t:"Unfair Customer Rating",urgency:"MEDIUM — Affects order access and Top Dasher",color:"#F5A623",secs:[
      {h:"Rating caused by restaurant error",timing:"File after the rating posts — you need the order ID and timestamp first",msg:"Hello Dasher Support,\n\nI am requesting removal of a 1-star rating on order #[ORDER ID] from [DATE].\n\nThis rating was caused by a restaurant error, not my performance:\n- I received a sealed bag from the restaurant\n- I had no ability to inspect or verify the contents\n- My delivery was completed correctly and on time\n\nDoorDash policy allows removal of ratings that reflect factors outside the Dasher's control. A restaurant packing error falls directly within that policy. My rating before this was [X stars].\n\nPlease review and remove this rating.\n\nThank you.",w:"'Factors outside the Dasher's control' is the exact language in DoorDash's internal rating review policy. Using it gives the agent the justification to approve the removal."},
      {h:"Rating caused by wait time",timing:"File within 48 hours of the delivery — the agent can pull restaurant wait timestamps",msg:"Hello Dasher Support,\n\nI am requesting removal of a rating on order #[ORDER ID] from [DATE].\n\nThe customer left a low rating due to delivery time. I want to note:\n- The order was not ready at the restaurant until [TIME]\n- I waited [X] minutes at [restaurant name] before the order was ready\n- I delivered the order as quickly as possible once I had it\n\nRestaurant preparation delays are outside a Dasher's control per DoorDash policy. I am asking for this rating to be removed.\n\nThank you.",w:"DoorDash can see your pickup timestamp versus the order ready time. Naming the restaurant and the wait time gives the agent something concrete to verify."},
    ]},
    {e:"📉",t:"Completion Rate Wrongly Affected",urgency:"HIGH — Impacts Dasher tier and access",color:"#F43F5E",secs:[
      {h:"Completion rate dispute",timing:"File immediately — completion rate drops affect order access right away",msg:"Hello Dasher Support,\n\nMy completion rate has been negatively affected by a complaint on order #[ORDER ID] from [DATE] that I believe is incorrect.\n\nProof of successful delivery:\n- Delivery photo at [ADDRESS]\n- GPS data confirming I was at the address at [TIME]\n- App delivery confirmation\n\nMy completion rate directly affects my Dasher status and access to Top Dasher benefits and priority orders. I am asking that this complaint be reviewed and reversed if it is not supported by the evidence.\n\nThank you.",w:"Naming 'Dasher status,' 'Top Dasher,' and 'priority orders' shows the agent this has a real financial impact on you. That makes them more likely to escalate a reversal."},
    ]},
    {e:"🔄",t:"Escalation — Appeal Was Denied",urgency:"USE AFTER A FIRST DENIAL",color:"#8B5CF6",secs:[
      {h:"Second appeal to senior agent",timing:"Use only after your first appeal closes without resolution — typically 2–3 business days",msg:"Hello,\n\nI am following up on a previous Dasher support request regarding order #[ORDER ID] from [DATE].\n\nMy original appeal was not resolved to my satisfaction. I am requesting escalation to a senior Dasher account specialist because:\n- My delivery photo evidence was not properly reviewed\n- The complaint directly contradicts my GPS track, photo timestamp, and app delivery record\n- This complaint is continuing to impact my account standing and income\n\nI have been an active Dasher since [DATE] with a strong record. I am asking for a thorough senior review.\n\nThank you.",w:"Asking for a 'senior Dasher account specialist' routes your ticket to a different tier of review. Most drivers don't know to ask for this. It significantly improves your odds."},
    ]},
    {e:"⛔",t:"Account Deactivation Appeal",urgency:"HIGH — Submit as soon as possible",color:"#F43F5E",secs:[
      {h:"First-hour checklist — do this before you file",timing:"Do this first — evidence disappears fast",msg:"1. Screenshot the deactivation notice (email + in-app message), with timestamps visible\n2. Screenshot your current stats — rating, completion rate, trip count — before anything changes\n3. Save recent in-app message history — screenshots of the last few days of customer chats\n4. Export and back up any dashcam or Record My Ride footage from recent trips\n5. Screenshot your recent trip/delivery history with dates, times, and IDs\n6. Write down what happened in your own words — date, time, what was said — while it's fresh\n7. Do NOT delete the app — your history, photos, and messages live there\n8. Do NOT create a new account or let someone else drive on yours — that's a permanent ban",w:"Reviewers decide on evidence, not stories — and most of it disappears within days if you don't save it now. Every item on this list is something deactivated drivers wish they had saved."},
      {h:"General deactivation appeal",timing:"File as soon as you receive the deactivation notice — response windows are short",msg:"Hello Dasher Support,\n\nI am writing to appeal the deactivation of my Dasher account, which I received notice of on [DATE].\n\nI believe this deactivation was made in error. My record:\n- [X] deliveries completed with a [X]% completion rate\n- The incident cited: [describe briefly, factually]\n- Supporting evidence attached: [delivery photos / GPS records / in-app messages]\n\nI have consistently followed Dasher standards and maintained a strong rating. I am asking for:\n1. A full review of my account history and the specific incident cited\n2. Escalation to a senior account specialist if this appeal is denied\n\nThank you.",w:"Deactivation reviewers decide mostly on numbers, not stories. Open with your delivery count and completion rate — that frames everything after it. Saying the evidence is 'attached' obliges the reviewer to open it before deciding."},
    ]},
  ],
  ubereats:[
    {e:"🚫",t:"False Non-Delivery Complaint",urgency:"HIGH — Can affect your account standing",color:"#F43F5E",secs:[
      {h:"Standard non-delivery dispute",timing:"File within 48 hours — Uber's review queue deprioritizes older complaints",msg:"Hello Uber Eats Support,\n\nI am writing to dispute a non-delivery complaint on trip #[TRIP ID] from [DATE].\n\nI completed this delivery successfully. My documentation:\n- Delivery photo taken at [ADDRESS] at [TIME] — geotagged and timestamped\n- GPS trip data showing my location at the delivery address\n- In-app delivery confirmation record\n\nI am requesting:\n1. This complaint be reviewed against my photo and GPS trip data\n2. Any negative effect on my account or completion rate be reversed\n3. A review of this customer's complaint history if this is a pattern\n\nThank you.",w:"Uber support works from Trip IDs — include it in the first line. 'Geotagged and timestamped' tells the agent exactly what to look for in your photo record."},
      {h:"Contactless delivery — no knock requested",timing:"File within 24 hours of the complaint appearing on your account",msg:"Hello Uber Eats Support,\n\nI am disputing a complaint on trip #[TRIP ID] from [DATE].\n\nThe customer selected contactless delivery. Here is what happened:\n1. I arrived at [ADDRESS] at [TIME]\n2. I placed the order at the door as instructed — no knock or ring per the customer's preference\n3. I took and submitted a delivery photo\n4. The app confirmed delivery and a notification was sent\n\nI followed the customer's exact delivery instructions. Please review and remove this complaint.\n\nThank you.",w:"Uber Eats has a specific policy protecting drivers who follow contactless delivery instructions. Framing your appeal around 'the customer's delivery preference' invokes that policy directly."},
    ]},
    {e:"⭐",t:"Unfair Rating",urgency:"MEDIUM — Affects trip quality and earnings",color:"#F5A623",secs:[
      {h:"Rating caused by restaurant issue",timing:"File after the rating posts and shows on your account — not before",msg:"Hello Uber Eats Support,\n\nI am requesting removal of a low rating on trip #[TRIP ID] from [DATE].\n\nThis rating does not reflect my service. The customer was dissatisfied with [missing item / food quality / wait time], which was caused by the restaurant, not by me.\n\nI picked up a sealed order from [RESTAURANT NAME]. I had no way to inspect or modify the contents. My delivery was completed correctly.\n\nUber policy allows removal of ratings caused by factors outside the delivery partner's control. My rating before this was [X]. Please review and remove this rating.\n\nThank you.",w:"'Factors outside the delivery partner's control' mirrors Uber's internal review language. Naming the restaurant specifically gives the agent something to verify independently."},
    ]},
    {e:"🔄",t:"Escalation — First Appeal Denied",urgency:"USE AFTER A FIRST DENIAL",color:"#8B5CF6",secs:[
      {h:"Escalate to senior specialist",msg:"Hello,\n\nI am following up on a previous request about Uber Eats trip #[TRIP ID] from [DATE].\n\nMy initial appeal was not resolved. I am requesting escalation to a senior account specialist for a full review because:\n- My photo and GPS evidence were not properly evaluated\n- The complaint contradicts my documented delivery record\n- This is continuing to affect my account and income\n\nI have been an Uber delivery partner since [DATE] with a strong track record. I am asking for a thorough review.\n\nThank you.",w:"Asking for 'senior account specialist' by name triggers a routing change. Most drivers exhaust themselves on first-tier agents — this one request often gets a different result."},
    ]},
    {e:"⛔",t:"Account Deactivation Appeal",urgency:"HIGH — Submit as soon as possible",color:"#F43F5E",secs:[
      {h:"First-hour checklist — do this before you file",timing:"Do this first — evidence disappears fast",msg:"1. Screenshot the deactivation notice (email + in-app message), with timestamps visible\n2. Screenshot your current stats — rating, completion rate, trip count — before anything changes\n3. Save recent in-app message history — screenshots of the last few days of customer chats\n4. Export and back up any dashcam or Record My Ride footage from recent trips\n5. Screenshot your recent trip/delivery history with dates, times, and IDs\n6. Write down what happened in your own words — date, time, what was said — while it's fresh\n7. Do NOT delete the app — your history, photos, and messages live there\n8. Do NOT create a new account or let someone else drive on yours — that's a permanent ban",w:"Reviewers decide on evidence, not stories — and most of it disappears within days if you don't save it now. Every item on this list is something deactivated drivers wish they had saved."},
      {h:"General deactivation appeal",timing:"File as soon as you receive the deactivation notice — response windows are short",msg:"Hello Uber Eats Support,\n\nI am writing to appeal the deactivation of my delivery partner account, received on [DATE].\n\nI believe this decision was made in error. My record:\n- [X] trips completed with a [X]% satisfaction rate\n- The incident cited: [describe briefly, factually]\n- Evidence available: [delivery photos / GPS trip data / in-app message log]\n\nI have consistently met Uber's community standards. I am asking for:\n1. A full review of my trip history and the specific incident cited\n2. Escalation to a senior specialist if this appeal is denied\n\nThank you.",w:"File through the in-app deactivation appeal flow, not general chat — account decisions go through a different review queue. Lead with your trip count and satisfaction rate; reviewers scan numbers first."},
    ]},
    {e:"🚨",t:"False Safety Report Appeal",urgency:"HIGH — Respond within 24 hours",color:"#F43F5E",secs:[
      {h:"Dispute a false safety or impairment report",timing:"Respond within 24 hours — safety reports can trigger automatic account restrictions before any human reviews them",msg:"Hello [Platform] Support,\n\nI am writing to dispute a safety report filed against me on [trip/order #] from [DATE].\n\nThis report is inaccurate. Here is what I can document:\n- GPS data showing the correct route with no unusual stops\n- [Dashcam / Record My Ride] footage covering the full trip\n- In-app message log showing normal, professional communication\n\nI take safety reports seriously, which is exactly why I am responding with evidence rather than just a denial. I am requesting:\n1. A full review of this report against my GPS, video, and message records\n2. Confirmation that this report will not affect my standing once reviewed\n3. Escalation to the safety review team if the first review does not clear this\n\nThank you.",w:"Safety reports are the one category where speed matters more than polish — a documented response inside 24 hours gives you the best shot at stopping an automatic restriction. Video evidence ends these disputes faster than any written argument."},
    ]},
  ],
  spark:[
    {e:"🚫",t:"False Non-Delivery Complaint",urgency:"HIGH — Can affect Spark Driver standing",color:"#F43F5E",secs:[
      {h:"Standard non-delivery dispute",msg:"Hello Spark Driver Support,\n\nI am writing to dispute a non-delivery complaint on delivery #[DELIVERY ID] from [DATE].\n\nThis delivery was completed successfully. My documentation:\n- Delivery photo showing the order placed at [ADDRESS]\n- GPS data confirming my location at the delivery address at [TIME]\n- App delivery confirmation timestamp\n\nI am requesting:\n1. This complaint be reviewed against my delivery photo and GPS record\n2. Any negative impact on my driver rating or standing be reversed\n\nThank you.",w:"Spark support uses Delivery IDs to pull records. Include it in the first line. Spark's team is smaller than DoorDash's — follow up after 48 hours if you don't hear back."},
    ]},
    {e:"📦",t:"Missing or Substituted Item Dispute",urgency:"HIGH — Common Spark-specific complaint",color:"#F43F5E",secs:[
      {h:"Item was out of stock — you followed protocol",msg:"Hello Spark Driver Support,\n\nI am writing to dispute a complaint about a missing item on delivery #[DELIVERY ID] from [DATE].\n\nThe item [ITEM NAME] was not available at the Walmart store. I handled this correctly:\n- Marked the item as unavailable in the Spark app\n- Selected an approved substitution / notified the customer of unavailability\n- Messaged the customer through the app before checking out\n\nI followed Spark's out-of-stock protocol exactly. Please review my in-app actions for this batch and remove this complaint.\n\nThank you.",w:"Spark agents can see exactly what you did in the app — when you marked items unavailable, when you messaged the customer, when you checked out. This appeal points them directly to that record."},
    ]},
    {e:"🔄",t:"Escalation — Appeal Was Denied",urgency:"USE AFTER A FIRST DENIAL",color:"#8B5CF6",secs:[
      {h:"Escalate to senior review",msg:"Hello,\n\nI am following up on a previous Spark Driver support request about delivery #[DELIVERY ID] from [DATE].\n\nMy initial request was denied. I am requesting a senior review because:\n- My delivery photo and GPS record were not properly evaluated\n- My in-app actions for this batch were not reviewed against the complaint\n- This complaint is unfairly affecting my driver rating and access to batches\n\nI have been a Spark Driver since [DATE] with a positive record. I am asking for a full review.\n\nThank you.",w:"Following up with a senior review request — and citing your tenure — often breaks through the first-tier denial cycle."},
    ]},
    {e:"⛔",t:"Account Deactivation Appeal",urgency:"HIGH — Submit as soon as possible",color:"#F43F5E",secs:[
      {h:"First-hour checklist — do this before you file",timing:"Do this first — evidence disappears fast",msg:"1. Screenshot the deactivation notice (email + in-app message), with timestamps visible\n2. Screenshot your current stats — rating, completion rate, trip count — before anything changes\n3. Save recent in-app message history — screenshots of the last few days of customer chats\n4. Export and back up any dashcam or Record My Ride footage from recent trips\n5. Screenshot your recent trip/delivery history with dates, times, and IDs\n6. Write down what happened in your own words — date, time, what was said — while it's fresh\n7. Do NOT delete the app — your history, photos, and messages live there\n8. Do NOT create a new account or let someone else drive on yours — that's a permanent ban",w:"Reviewers decide on evidence, not stories — and most of it disappears within days if you don't save it now. Every item on this list is something deactivated drivers wish they had saved."},
      {h:"General deactivation appeal",timing:"File as soon as you receive the deactivation notice — response windows are short",msg:"Hello Spark Driver Support,\n\nI am writing to appeal the deactivation of my Spark Driver account, received on [DATE].\n\nI believe this decision was made in error. My record:\n- [X] deliveries completed, On-Time Arrival [X]%, Completion Rate [X]%\n- The incident cited: delivery #[DELIVERY ID] on [DATE] — [describe briefly, factually]\n- Evidence available: [delivery photo / GPS record / in-app messages]\n\nI have met Spark's driver standards consistently. I am asking for:\n1. A full review of my metrics and the specific delivery cited\n2. Escalation to a senior review if this appeal is denied\n\nThank you.",w:"Spark's review starts at your My Metrics screen. Put your On-Time Arrival and Completion Rate numbers inside the appeal itself — if the reviewer has to open another tab to find them, you've already lost momentum."},
    ]},
  ],
  instacart:[
    {e:"🚫",t:"False Non-Delivery Complaint",urgency:"HIGH — Can affect Shopper access",color:"#F43F5E",secs:[
      {h:"Standard non-delivery dispute",msg:"Hello Instacart Support,\n\nI am writing to dispute a non-delivery complaint on batch #[BATCH ID] from [DATE].\n\nI completed this delivery successfully. My evidence:\n- Delivery photo showing the bags at [ADDRESS]\n- GPS data confirming I was at the delivery location at [TIME]\n- App delivery confirmation record\n- All items in this batch were scanned and verified\n\nI am requesting:\n1. This complaint be reviewed against my delivery photo and GPS data\n2. Any impact on my Shopper rating or standing be reversed\n\nThank you.",w:"'Batch ID' is the Instacart-specific term. Including 'all items were scanned' adds a data point agents can verify against the scan record — unique to Instacart and very strong evidence."},
    ]},
    {e:"📦",t:"Missing Item or Wrong Item Dispute",urgency:"HIGH — Most common Instacart complaint",color:"#F43F5E",secs:[
      {h:"Item was out of stock — you followed protocol",msg:"Hello Instacart Support,\n\nI am disputing a complaint about a missing item on batch #[BATCH ID] from [DATE].\n\nThe item [ITEM NAME] was not available at [STORE NAME]. I handled this correctly:\n- Marked the item as out of stock in the Instacart app at [TIME]\n- Selected an approved replacement / left the item unfulfilled per the customer's preference\n- Messaged the customer through the app before checking out\n\nMy in-app actions for this batch show I followed Instacart's out-of-stock protocol exactly. Please review my batch activity and remove this complaint.\n\nThank you.",w:"Instacart's batch activity log shows every action you took. This appeal directs the agent to that log, which is far more convincing than a verbal account."},
    ]},
    {e:"🔄",t:"Escalation — First Appeal Denied",urgency:"USE AFTER A FIRST DENIAL",color:"#8B5CF6",secs:[
      {h:"Senior review request",msg:"Hello,\n\nI am following up on a previous Instacart support request about batch #[BATCH ID] from [DATE].\n\nMy first appeal was denied. I am requesting escalation to a senior Shopper support specialist because:\n- My delivery photo and batch activity log were not fully reviewed\n- The complaint contradicts my documented in-app actions\n- This is continuing to affect my Shopper rating and batch access\n\nI have been an active Instacart Shopper since [DATE] with a strong record. I am asking for a complete review.\n\nThank you.",w:"Requesting a 'senior Shopper support specialist' by that title moves your ticket past first-tier agents who use scripted responses."},
    ]},
    {e:"⛔",t:"Account Deactivation Appeal",urgency:"HIGH — Submit as soon as possible",color:"#F43F5E",secs:[
      {h:"First-hour checklist — do this before you file",timing:"Do this first — evidence disappears fast",msg:"1. Screenshot the deactivation notice (email + in-app message), with timestamps visible\n2. Screenshot your current stats — rating, completion rate, trip count — before anything changes\n3. Save recent in-app message history — screenshots of the last few days of customer chats\n4. Export and back up any dashcam or Record My Ride footage from recent trips\n5. Screenshot your recent trip/delivery history with dates, times, and IDs\n6. Write down what happened in your own words — date, time, what was said — while it's fresh\n7. Do NOT delete the app — your history, photos, and messages live there\n8. Do NOT create a new account or let someone else drive on yours — that's a permanent ban",w:"Reviewers decide on evidence, not stories — and most of it disappears within days if you don't save it now. Every item on this list is something deactivated drivers wish they had saved."},
      {h:"General deactivation appeal",timing:"File as soon as you receive the deactivation notice — response windows are short",msg:"Hello Instacart Support,\n\nI am writing to appeal the deactivation of my Shopper account, received on [DATE].\n\nI believe this decision was made in error. My record:\n- [X] batches completed with a [X]-star rating\n- The incident cited: [describe briefly, factually]\n- Evidence available: [delivery photos / batch activity log / customer messages]\n\nI have followed Instacart's shopper guidelines on every batch. I am asking for:\n1. A full review of my batch history and the specific incident cited\n2. Escalation to a senior Shopper support specialist if this appeal is denied\n\nThank you.",w:"Instacart reviewers can pull your full batch activity log — every scan, message, and timestamp. Point them at specific clean batches instead of describing yourself as reliable. The log convinces more than any adjective."},
    ]},
  ],  amazonflex:[
    {e:"🚫",t:"False 'Never Received' / Missing Package",urgency:"HIGH — Directly affects your standing",color:"#F43F5E",secs:[
      {h:"Standard missing package appeal",msg:"Hello Amazon Flex Support,\n\nI am appealing a missing package complaint on Block [BLOCK ID] for package TBA [TBA NUMBER] delivered on [DATE].\n\nThis delivery was completed successfully. My documentation:\n- Delivery photo taken through the Amazon Flex app showing the package at the customer's door\n- GPS data confirming I was at the delivery address at [TIME]\n- App delivery confirmation record\n\nI request this complaint be reviewed and removed from my standing.\n\nThank you.",w:"Always include Block ID + TBA. Amazon support can pull your exact GPS and photo records."},
      {h:"Multi-package block with one complaint",msg:"Hello Amazon Flex Support,\n\nI am appealing a missing package complaint on Block [BLOCK ID] for TBA [TBA NUMBER].\n\nAll other packages in this block were successfully delivered. I have:\n- Photo proof for this stop\n- GPS confirmation at the address\n\nThis appears to be an isolated false claim. Please remove the ding from my standing.\n\nThank you.",w:"Amazon often removes single-package dings when the rest of the block is clean."},
    ]},
    {e:"⭐",t:"Unfair Standing / Rating Ding",urgency:"MEDIUM",color:"#F5A623",secs:[
      {h:"Photo was taken but still dinged",msg:"Hello,\n\nI am requesting removal of a delivery ding on Block [BLOCK ID], TBA [TBA NUMBER].\n\nI followed all procedures and took a delivery photo through the app. GPS confirms I was at the address. Please review the attached photo and GPS data and remove this from my standing.\n\nThank you.",w:"Emphasize that you used the in-app photo — this is the strongest evidence Amazon accepts."},
    ]},
    {e:"🔄",t:"Escalation — Appeal Denied",urgency:"USE AFTER FIRST DENIAL",color:"#8B5CF6",secs:[
      {h:"Request senior review",msg:"Hello,\n\nI am following up on a previous appeal for Block [BLOCK ID] / TBA [TBA NUMBER].\n\nMy initial appeal was denied, but my delivery photo and GPS records clearly show the package was delivered. I request escalation to a senior specialist for full review.\n\nThank you.",w:"Asking for 'senior specialist' often gets a fresh set of eyes on your case."},
    ]},
  ],
  lyft:[
    {e:"⭐",t:"Unfair Low Rating",urgency:"HIGH — Affects ride access and priority",color:"#F43F5E",secs:[
      {h:"Rating caused by factors outside your control",timing:"File after the rating posts and your average drops — Lyft can't remove a rating before it appears",msg:"Hello Lyft Support,\n\nI am requesting removal of a low rating on trip #[TRIP ID] from [DATE].\n\nThis rating does not reflect my actual service. It appears to have been caused by [traffic delay / GPS navigation error / long pickup wait], which was outside my control as a driver.\n\nMy overall rating and driving history show consistent, professional service. Lyft's policy allows review of ratings caused by external factors. Please review and remove this rating.\n\nThank you.",w:"Always include the Trip ID — agents can't pull your record without it. 'Outside my control as a driver' is the exact framing Lyft's review team looks for when deciding whether to remove a rating."},
      {h:"Rating caused by a false complaint",msg:"Hello Lyft Support,\n\nI am requesting review of a low rating and complaint on trip #[TRIP ID] from [DATE].\n\nThe complaint states [describe complaint briefly]. This did not happen. Here is what actually occurred:\n[Brief, factual account — where you picked up, route taken, drop-off location, how the ride felt]\n\nI have been a Lyft driver since [DATE] with a consistent record. This complaint is inaccurate and is affecting my standing unfairly. I am asking for a review of the trip GPS data and a removal of this rating.\n\nThank you.",w:"Keep your account brief and factual — no emotion. Lyft agents check GPS routes and timestamps, not narratives. A clean factual timeline is far more persuasive than a long explanation."},
    ]},
    {e:"🚨",t:"Passenger Misconduct Report",urgency:"FILE IMMEDIATELY — Protects your safety record",color:"#F43F5E",secs:[
      {h:"Reporting harassment or threatening behavior",timing:"File the same day — safety reports are prioritized when filed promptly",msg:"Hello Lyft Safety Team,\n\nI am filing a safety report regarding a passenger on trip #[TRIP ID] from [DATE].\n\nWhat happened:\n[Describe clearly — what was said or done, when in the ride it occurred, how you responded, and where you ended the ride if applicable]\n\nI am requesting:\n1. This incident be documented in the passenger's account\n2. A review of whether this passenger should be flagged for future rides\n3. Confirmation that this report will not negatively affect my standing\n\nThank you.",w:"File this the same day. Addressing it to 'Lyft Safety Team' routes it to a specialized department. Passenger misconduct reports are permanently noted and Lyft takes them seriously — but you must file promptly."},
    ]},
    {e:"❌",t:"Cancellation Dispute",urgency:"MEDIUM — Protects your cancellation rate",color:"#F5A623",secs:[
      {h:"Cancellation fee not received — passenger was a no-show",timing:"File within 24 hours — GPS arrival data is clearest right after the ride",msg:"Hello Lyft Support,\n\nI am requesting review of a missed cancellation fee on trip #[TRIP ID] from [DATE].\n\nI arrived at the pickup location at [TIME] and waited the required time before cancelling. The passenger did not appear and did not message me through the app.\n\nMy GPS confirms I was at [PICKUP ADDRESS] for the required wait period. I am requesting the appropriate cancellation fee be credited to my account.\n\nThank you.",w:"Lyft can verify your GPS arrival time and how long you waited. Most no-show cancellation disputes resolve in the driver's favor when your GPS confirms you were at the pin."},
    ]},
    {e:"🔄",t:"Escalation — Appeal Denied",urgency:"USE AFTER FIRST DENIAL",color:"#8B5CF6",secs:[
      {h:"Request senior account review",msg:"Hello,\n\nI am following up on a previous Lyft support request about trip #[TRIP ID] from [DATE].\n\nMy initial request was not resolved. I am asking for escalation to a senior driver account specialist.\n\nThe original issue: [brief summary — one sentence]\n\nThis is continuing to affect my driver rating and income. I have been a Lyft driver since [DATE] with a strong record and I am asking for a complete, fair review.\n\nThank you.",w:"'Senior driver account specialist' routes your ticket past first-tier support. Most drivers give up after a first denial — this one follow-up often gets a different result."},
    ]},
    {e:"⛔",t:"Account Deactivation Appeal",urgency:"HIGH — Submit as soon as possible",color:"#F43F5E",secs:[
      {h:"First-hour checklist — do this before you file",timing:"Do this first — evidence disappears fast",msg:"1. Screenshot the deactivation notice (email + in-app message), with timestamps visible\n2. Screenshot your current stats — rating, completion rate, trip count — before anything changes\n3. Save recent in-app message history — screenshots of the last few days of customer chats\n4. Export and back up any dashcam or Record My Ride footage from recent trips\n5. Screenshot your recent trip/delivery history with dates, times, and IDs\n6. Write down what happened in your own words — date, time, what was said — while it's fresh\n7. Do NOT delete the app — your history, photos, and messages live there\n8. Do NOT create a new account or let someone else drive on yours — that's a permanent ban",w:"Reviewers decide on evidence, not stories — and most of it disappears within days if you don't save it now. Every item on this list is something deactivated drivers wish they had saved."},
      {h:"General deactivation appeal",timing:"File as soon as you receive the deactivation notice — response windows are short",msg:"Hello Lyft Support,\n\nI am writing to appeal the deactivation of my Lyft driver account, received on [DATE].\n\nI believe this decision was made in error. My record:\n- [X] rides completed with a [X]-star rating\n- The incident cited: trip #[TRIP ID] on [DATE] — [describe briefly, factually]\n- Evidence available: [GPS route data / dashcam footage / in-app messages]\n\nI have driven to Lyft's standards throughout. I am asking for:\n1. A full review of my driving history and the specific trip cited\n2. Escalation to a senior driver account specialist if this appeal is denied\n\nThank you.",w:"Lyft weighs recent history heaviest in deactivation reviews. If the cited incident is old and your recent record is clean, say so in the first paragraph — don't make the reviewer dig for it."},
    ]},
    {e:"🚨",t:"False Safety Report Appeal",urgency:"HIGH — Respond within 24 hours",color:"#F43F5E",secs:[
      {h:"Dispute a false safety or impairment report",timing:"Respond within 24 hours — safety reports can trigger automatic account restrictions before any human reviews them",msg:"Hello [Platform] Support,\n\nI am writing to dispute a safety report filed against me on [trip/order #] from [DATE].\n\nThis report is inaccurate. Here is what I can document:\n- GPS data showing the correct route with no unusual stops\n- [Dashcam / Record My Ride] footage covering the full trip\n- In-app message log showing normal, professional communication\n\nI take safety reports seriously, which is exactly why I am responding with evidence rather than just a denial. I am requesting:\n1. A full review of this report against my GPS, video, and message records\n2. Confirmation that this report will not affect my standing once reviewed\n3. Escalation to the safety review team if the first review does not clear this\n\nThank you.",w:"Safety reports are the one category where speed matters more than polish — a documented response inside 24 hours gives you the best shot at stopping an automatic restriction. Video evidence ends these disputes faster than any written argument."},
    ]},
  ],
  amazonflex:[
    {e:"⛔",t:"Account Deactivation Appeal",urgency:"HIGH — Submit as soon as possible",color:"#F43F5E",secs:[
      {h:"First-hour checklist — do this before you file",timing:"Do this first — evidence disappears fast",msg:"1. Screenshot the deactivation notice (email + in-app message), with timestamps visible\n2. Screenshot your current stats — rating, completion rate, trip count — before anything changes\n3. Save recent in-app message history — screenshots of the last few days of customer chats\n4. Export and back up any dashcam or Record My Ride footage from recent trips\n5. Screenshot your recent trip/delivery history with dates, times, and IDs\n6. Write down what happened in your own words — date, time, what was said — while it's fresh\n7. Do NOT delete the app — your history, photos, and messages live there\n8. Do NOT create a new account or let someone else drive on yours — that's a permanent ban",w:"Reviewers decide on evidence, not stories — and most of it disappears within days if you don't save it now. Every item on this list is something deactivated drivers wish they had saved."},
      {h:"General deactivation appeal",timing:"File as soon as you receive the deactivation notice — response windows are short",msg:"Hello Amazon Flex Support,\n\nI am writing to appeal the deactivation of my Amazon Flex account, received on [DATE].\n\nI believe this decision was made in error. My record:\n- Standing: [Fantastic/Great] across my recent blocks\n- The incident cited: Block [BLOCK ID], TBA [TBA NUMBER] — [describe briefly, factually]\n- Evidence: [in-app delivery photo / GPS record for this stop]\n\nI have followed Flex delivery procedures on every block. I am asking for:\n1. A full review of my standing history and the specific block cited\n2. Escalation to a senior specialist if this appeal is denied\n\nThank you.",w:"Flex deactivation appeals run on email, not the app — and reviewers notice whether you wrote the same day. A same-day email signals you take it seriously. Always include Block ID and TBA so they can pull the exact stop."},
    ]},
  ],
  uber:[
    {e:"⭐",t:"Unfair Passenger Rating",urgency:"MEDIUM — Affects standing and Uber Pro tier",color:"#F5A623",secs:[
      {h:"Rating caused by traffic, navigation, or price",timing:"File after the rating posts — Uber can't remove a rating that hasn't appeared yet",msg:"Hello Uber Support,\n\nI am requesting removal of a low rating on trip #[TRIP ID] from [DATE].\n\nBased on the timing and any comments left, I believe the passenger rated me low due to [traffic delay / navigation issue / trip price] — none of which are within my control as a driver.\n\nUber's rating policy explicitly excludes ratings caused by traffic, navigation, pricing, and other factors outside driver control. I am asking for this rating to be reviewed and removed under that policy.\n\nThank you.",w:"Price complaints, traffic frustration, and navigation errors are explicitly listed in Uber's rating exclusion policy. Naming the specific category gives the agent a clear policy anchor to approve the removal."},
      {h:"Rating from a passenger who consistently rates drivers low",msg:"Hello Uber Support,\n\nI am requesting a review of a low rating received on trip #[TRIP ID] from [DATE].\n\nI completed this trip professionally and safely. I am requesting review because I believe this rating may not reflect a genuine service issue.\n\nUber's policy allows exclusion of ratings from riders who consistently rate drivers low. Please review this passenger's rating history and consider removal if the pattern applies.\n\nMy rating before this was [X stars]. Thank you.",w:"Uber's system already automatically excludes some low ratings from frequent low-raters. This letter accelerates that review by surfacing the concern explicitly. Keep it brief and factual."},
    ]},
    {e:"🚫",t:"False Complaint from Passenger",urgency:"HIGH — Can affect account standing",color:"#F43F5E",secs:[
      {h:"Dispute a passenger complaint",timing:"File within 24 hours — Uber can temporarily restrict accounts quickly after safety complaints",msg:"Hello Uber Support,\n\nI am writing to dispute a complaint filed against me on trip #[TRIP ID] from [DATE].\n\nI completed this trip professionally and safely. The complaint is inaccurate. Here is what I can document:\n- Passenger name was confirmed at pickup per Uber policy\n- GPS data confirms the correct route was taken\n- No incidents occurred during the trip\n\nI am requesting:\n1. A full review of this complaint against my trip record and GPS data\n2. Any negative impact on my account standing to be reversed\n3. A review of this passenger's complaint history if this is a pattern\n\nThank you.",w:"Lead with your documentation, not your denial. Agents review trip data, not arguments. Asking for a complaint history review signals that you understand the formal process — and that you're not going away after one response."},
    ]},
    {e:"🔄",t:"Escalation — First Appeal Denied",urgency:"USE AFTER A FIRST DENIAL",color:"#8B5CF6",secs:[
      {h:"Escalate to senior specialist",msg:"Hello,\n\nI am following up on a previous request about Uber trip #[TRIP ID] from [DATE].\n\nMy initial appeal was not resolved. I am requesting escalation to a senior account specialist because:\n- My GPS data and trip record were not properly reviewed\n- The complaint contradicts my documented trip history\n- This is continuing to affect my account standing and income\n\nI have been an Uber driver since [DATE] with a strong record. I am asking for a thorough review.\n\nThank you.",w:"Asking for 'senior account specialist' routes your ticket to a higher-tier review. Most drivers exhaust themselves on first-tier agents — this escalation request often gets a meaningfully different result."},
    ]},
    {e:"⛔",t:"Account Deactivation Appeal",urgency:"HIGH — Submit as soon as possible",color:"#F43F5E",secs:[
      {h:"First-hour checklist — do this before you file",timing:"Do this first — evidence disappears fast",msg:"1. Screenshot the deactivation notice (email + in-app message), with timestamps visible\n2. Screenshot your current stats — rating, completion rate, trip count — before anything changes\n3. Save recent in-app message history — screenshots of the last few days of customer chats\n4. Export and back up any dashcam or Record My Ride footage from recent trips\n5. Screenshot your recent trip/delivery history with dates, times, and IDs\n6. Write down what happened in your own words — date, time, what was said — while it's fresh\n7. Do NOT delete the app — your history, photos, and messages live there\n8. Do NOT create a new account or let someone else drive on yours — that's a permanent ban",w:"Reviewers decide on evidence, not stories — and most of it disappears within days if you don't save it now. Every item on this list is something deactivated drivers wish they had saved."},
      {h:"General deactivation appeal",timing:"File as soon as you receive the deactivation notice — response windows are short",msg:"Hello Uber Support,\n\nI am writing to appeal the deactivation of my Uber driver account, received on [DATE].\n\nI believe this decision was made in error. My record:\n- [X] trips completed with a [X]-star rating\n- The incident cited: trip #[TRIP ID] on [DATE] — [describe briefly, factually]\n- Evidence available: [GPS trip data / dashcam or Record My Ride footage / in-app messages]\n\nI have driven to Uber's community standards throughout. I am asking for:\n1. A full review of my trip history and the specific trip cited\n2. Escalation to a senior account specialist if this appeal is denied\n\nThank you.",w:"Quote the specific policy section named in your deactivation notice and answer that section directly. Vague appeals get vague denials — a point-by-point response gives the reviewer something concrete to overturn."},
    ]},
    {e:"🚨",t:"False Safety Report Appeal",urgency:"HIGH — Respond within 24 hours",color:"#F43F5E",secs:[
      {h:"Dispute a false safety or impairment report",timing:"Respond within 24 hours — safety reports can trigger automatic account restrictions before any human reviews them",msg:"Hello [Platform] Support,\n\nI am writing to dispute a safety report filed against me on [trip/order #] from [DATE].\n\nThis report is inaccurate. Here is what I can document:\n- GPS data showing the correct route with no unusual stops\n- [Dashcam / Record My Ride] footage covering the full trip\n- In-app message log showing normal, professional communication\n\nI take safety reports seriously, which is exactly why I am responding with evidence rather than just a denial. I am requesting:\n1. A full review of this report against my GPS, video, and message records\n2. Confirmation that this report will not affect my standing once reviewed\n3. Escalation to the safety review team if the first review does not clear this\n\nThank you.",w:"Safety reports are the one category where speed matters more than polish — a documented response inside 24 hours gives you the best shot at stopping an automatic restriction. Video evidence ends these disputes faster than any written argument."},
    ]},
  ],
  gopuff:[
    {e:"🚫",t:"False Non-Delivery Complaint",urgency:"HIGH — Can affect account standing",color:"#F43F5E",secs:[
      {h:"Standard non-delivery dispute",msg:"Hello GoPuff Driver Support,\n\nI am writing to dispute a non-delivery complaint on order #[ORDER ID] from [DATE].\n\nI completed this delivery successfully. My documentation:\n- Delivery photo taken at [ADDRESS] showing the items at the door\n- GPS data confirming my location at [ADDRESS] at [TIME]\n- In-app delivery confirmation\n\nI am requesting:\n1. This complaint be reviewed against my photo and GPS data\n2. Any negative impact on my driver account be reversed\n\nThank you.",w:"GoPuff support reviews photo and GPS data the same way other platforms do. Lead with your evidence — photo first, then GPS, then app confirmation. Keep it factual and brief."},
    ]},
    {e:"⛔",t:"Account Deactivation Appeal",urgency:"HIGH — Submit as soon as possible",color:"#F43F5E",secs:[
      {h:"First-hour checklist — do this before you file",timing:"Do this first — evidence disappears fast",msg:"1. Screenshot the deactivation notice (email + in-app message), with timestamps visible\n2. Screenshot your current stats — rating, completion rate, trip count — before anything changes\n3. Save recent in-app message history — screenshots of the last few days of customer chats\n4. Export and back up any dashcam or Record My Ride footage from recent trips\n5. Screenshot your recent trip/delivery history with dates, times, and IDs\n6. Write down what happened in your own words — date, time, what was said — while it's fresh\n7. Do NOT delete the app — your history, photos, and messages live there\n8. Do NOT create a new account or let someone else drive on yours — that's a permanent ban",w:"Reviewers decide on evidence, not stories — and most of it disappears within days if you don't save it now. Every item on this list is something deactivated drivers wish they had saved."},
      {h:"General deactivation appeal",timing:"File as soon as you receive the deactivation notice — response windows are short",msg:"Hello GoPuff Driver Support,\n\nI am writing to appeal the deactivation of my GoPuff driver account, which I received notice of on [DATE].\n\nI believe this deactivation was made in error. Here is my account of the situation:\n- [Describe what happened, factually and briefly]\n- I have always followed GoPuff's Community Guidelines regarding Safety, Respect, and Integrity\n- I have completed [X] deliveries on the platform with a clean record\n\nI am asking for a full review of my account history and the specific incident cited. I am committed to GoPuff's standards and would appreciate the opportunity to continue.\n\nThank you.",w:"GoPuff's stated deactivation grounds are violations of Safety, Respect, or Integrity. Frame your appeal around your compliance with those three categories. Note your delivery count — drivers with a long, clean record get more benefit of the doubt."},
      {h:"Deactivation caused by a Checkr background check error",msg:"Hello GoPuff Driver Support,\n\nI am appealing my account deactivation, which I believe was triggered by an error in my Checkr background check.\n\nI have reviewed my results and believe the following item is inaccurate:\n- [Describe the specific item in dispute]\n\nI have submitted a dispute directly with Checkr at consumer.checkr.com. Under the Fair Credit Reporting Act, I have the right to dispute inaccurate background information.\n\nI am asking GoPuff to hold my deactivation pending the outcome of my Checkr dispute. I can provide documentation of my dispute submission upon request.\n\nThank you.",w:"Background check errors via Checkr are one of the most common causes of GoPuff deactivation. File the Checkr dispute first, then reference it in your GoPuff appeal. This creates a paper trail and gives the platform a reason to wait before making the deactivation permanent."},
    ]},
  ],
};

var PLATFORM_CHECKLISTS = {
  doordash:[
    {e:"📸",t:"Delivery photo taken — door and bags visible"},
    {e:"💬",t:"Customer messaged through DoorDash app"},
    {e:"📍",t:"GPS was active the entire delivery"},
    {e:"📋",t:"Order marked delivered in the app"},
    {e:"🖼️",t:"Delivery confirmation screen screenshotted"},
    {e:"📝",t:"Order number noted if anything felt off"},
  ],
  ubereats:[
    {e:"📸",t:"Photo submitted through Uber Eats app"},
    {e:"💬",t:"Customer messaged in-app (not SMS)"},
    {e:"📍",t:"GPS active for the full trip"},
    {e:"🆔",t:"Trip ID screenshotted if anything went wrong"},
    {e:"📋",t:"Delivery confirmed in the Uber Eats app"},
    {e:"⏱️",t:"Long restaurant wait documented with a customer message"},
  ],
  spark:[
    {e:"📸",t:"Delivery photo taken showing all bags at door"},
    {e:"💬",t:"Customer messaged via Spark app about any changes"},
    {e:"📍",t:"GPS active throughout the trip"},
    {e:"📋",t:"Delivery confirmed in the Spark app"},
    {e:"🛒",t:"Any out-of-stock items marked in app before checkout"},
    {e:"🧾",t:"Delivery summary screenshotted after completion"},
  ],
  instacart:[
    {e:"📸",t:"Delivery photo submitted in the Instacart app"},
    {e:"🛒",t:"All available items scanned in store"},
    {e:"💬",t:"Customer messaged in-app about any substitutions"},
    {e:"📍",t:"GPS active throughout the entire batch"},
    {e:"📋",t:"Batch confirmed complete in the app"},
    {e:"🧾",t:"Batch summary screenshotted after delivery"},
  ],  lyft:[
    {e:"🪪",t:"Confirmed passenger's name before they entered the car"},
    {e:"📱",t:"GPS active and phone mounted before the ride began"},
    {e:"🚗",t:"Car was clean and free of strong odors"},
    {e:"📋",t:"Trip ID screenshotted if anything felt off during the ride"},
    {e:"⭐",t:"Passenger rated 5 stars immediately after drop-off"},
    {e:"🔇",t:"Let the passenger set the conversation tone — no forced chat"},
  ],
  amazonflex:[
    {e:"📸",t:"Delivery photo taken in the Flex app"},
    {e:"📍",t:"GPS was active for the entire block"},
    {e:"🔢",t:"Scanned packages one address at a time (multi-stop blocks)"},
    {e:"🖼️",t:"Delivery confirmation screen screenshotted"},
    {e:"📋",t:"Block ID and TBA numbers noted if anything felt off"},
    {e:"🔄",t:"Any undeliverable packages returned with correct reason code"},
  ],
  uber:[
    {e:"🪪",t:"Confirmed passenger's name before they entered the car"},
    {e:"📱",t:"GPS active and phone mounted before the ride began"},
    {e:"🚗",t:"Car was clean and free of strong odors"},
    {e:"📋",t:"Trip ID screenshotted if anything felt off during the ride"},
    {e:"⭐",t:"Passenger rated 5 stars immediately after drop-off"},
    {e:"🔇",t:"Let the passenger set the conversation tone — no forced chat"},
  ],
  gopuff:[
    {e:"📦",t:"Order count verified at the facility before leaving"},
    {e:"📸",t:"Delivery photo taken — items at door with address visible"},
    {e:"📍",t:"GPS active for the full delivery"},
    {e:"💬",t:"Customer messaged through GoPuff app if any issue arose"},
    {e:"📋",t:"Order ID noted if anything felt off during delivery"},
  ],
};

