// DropPilot content data (extracted from app.html). Loaded before the app script.

// Do not edit structure; content edits go through the normal content workflow.

var ALL_TIPS_ES = [
  {e:"👋",t:"Saluda con una sonrisa",s:"La primera impresión decide tu calificación.",d:"Breve contacto visual, di algo simple — '¡Hola, aquí está tu pedido!' No necesitas hablar mucho. Solo sé amable. Los clientes califican más alto a los repartidores que parecen personas reales que a los que entregan en silencio y se van."},
  {e:"🔔",t:"Nunca toques en pedidos sin contacto",s:"Una de las causas principales de calificaciones de 1 estrella.",d:"Si el cliente eligió 'Dejar en la puerta', NO toques ni timbres. Deja la comida ordenadamente, foto, marca entregado. Eligió sin contacto por una razón. Respetarlo demuestra que leíste sus instrucciones — eso gana 5 estrellas."},
  {e:"📸",t:"Foto en cada entrega",s:"Tu foto es tu protección. Sin excepciones.",d:"Foto clara mostrando la comida Y la puerta o número de casa juntos. Te protege si un cliente alguna vez dice que no recibió su pedido. Cada vez — buen tiempo, mal tiempo, de día o de noche."},
  {e:"💬",t:"Avisa cuando estés a 3 minutos",s:"Gana más 5 estrellas que casi cualquier otro hábito.",d:"Un rápido '¡Hola! A unos 3 minutos con tu pedido!' establece un tono profesional antes de llegar. Los clientes que saben que vienes casi siempre califican más alto. 10 segundos."},
  {e:"🌡️",t:"Maneja la comida como si fuera tuya",s:"Cómo cargas la bolsa les dice todo.",d:"Comida caliente llega caliente. Bolsas no aplastadas. Bebidas derechas. Estos detalles le dicen al cliente si te importó. Los repartidores que cuidan cada pedido reciben las mejores propinas."},
  {e:"⚡",t:"Puerta equivocada = cuenta perdida",s:"La velocidad no sirve en la dirección equivocada.",d:"Entregar en la dirección equivocada es de las formas más rápidas de perder tu cuenta. 5 segundos para confirmar antes de bajar del auto. Esos 5 segundos protegen toda tu permanencia en la plataforma."},
  {e:"🤐",t:"Nunca te quejes con el cliente",s:"Tu mal día no es su problema.",d:"Espera larga, tráfico, problemas con la app — el cliente no causó nada de eso y no quiere escucharlo. Mantén cada interacción cálida sin importar cómo va el turno. Ellos solo están contentos de que su comida llegó."},
  {e:"🎁",t:"Pequeños extras = mejores propinas",s:"Servilletas extra. Bolsa nivelada. Mano firme.",d:"Servilletas extra, bolsa nivelada, bebidas aseguradas — nada toma más de unos segundos. Pero los clientes lo notan. Y dan propina a los repartidores que claramente prestaron atención."},
  {e:"🚪",t:"Sin contacto significa cero contacto",s:"Sin tocar. Sin timbre. Entrega limpia.",d:"Dejar en la puerta significa exactamente eso. Deja la comida ordenadamente, foto, confirma. Un toque en un pedido sin contacto es de las razones más comunes por las que buenos repartidores reciben 1 estrella inesperada."},
  {e:"📞",t:"Cuando algo sale mal — mensaje primero",s:"Un mensaje proactivo previene una mala reseña.",d:"¿Código de acceso faltante? ¿No encuentras la unidad? ¿Nadie responde? Mensaje antes de llamar o irte. Un mensaje tranquilo le da al cliente la oportunidad de ayudar — y demuestra que intentaste. Ese esfuerzo casi siempre protege tu calificación."},
];

var LEARN_CATS_ES = [
  {
    e:"🧠", t:"Leer a las personas", sub:"Psicología simple que puedes usar ahora mismo", free:true,
    secs:[
      {h:"La entrega y la despedida", body:"La gente no recuerda toda la entrega. Recuerda dos momentos — la entrega y la despedida. Domina esos dos y te califican con 5 estrellas incluso después de una larga espera. Todo lo demás es ruido. Antes de cada entrega, recuérdate: entrega, despedida. Esos son los dos momentos que deciden tu calificación.", tip:"Dos momentos lo deciden todo. La entrega. La despedida."},
      {h:"Usa su nombre una vez", body:"Tu app muestra el primer nombre del cliente. La mayoría de los conductores lo ignoran. Gran error — escuchar tu propio nombre cambia el momento de 'atendido' a 'visto'. Úsalo exactamente una vez: 'Aquí tienes, Marcus — ¡que disfrutes tu comida!' Una vez se siente cálido. Dos veces se siente raro. Tres veces se siente incómodo.", tip:"Una vez. No dos. Nunca tres."},
      {h:"Lee, iguala, refleja", body:"Algunos clientes escriben informal: 'yo food almost here??' Otros son formales: 'Could you provide an estimated arrival time?' La mayoría de los conductores les envía el mismo mensaje a todos. Mejor refleja su estilo. Informal → informal. Formal → educado. Se sienten comprendidos sin saber por qué.", tip:"Lee su mensaje. Iguala su tono. Refléjalo."},
    ]
  },
  {
    e:"🚪", t:"En la puerta", sub:"Pequeños hábitos que cambian cómo te ven los clientes", free:true,
    secs:[
      {h:"Hazte a un lado, baja un escalón", body:"No te pares justo en el centro — se siente agresivo, como si los estuvieras bloqueando. Párate un poco hacia un lado. Sostén la bolsa extendida. En escalones, párate un escalón debajo del de arriba. Estar un poco más bajo que el cliente se lee como amable, no imponente. La posición misma dice 'vine a darte algo', no 'estoy en tu camino.'", tip:"Hazte a un lado. Baja un escalón. Extiende la bolsa."},
      {h:"Dos manos, a la altura del pecho", body:"Una mano colgando parece basura. Dos manos a la altura del pecho parece cuidado. Los clientes sienten la diferencia sin saber por qué. Regla: cualquier pedido con bebidas → dos manos, siempre niveladas. Esos 5 segundos extra se ganan la propina.", tip:"Dos manos. Altura del pecho. Siempre."},
      {h:"Pausa antes de irte", body:"Después de entregar la bolsa y despedirte, haz una pausa de medio segundo. Una mirada breve. Luego vete. Esa pequeña pausa convierte una entrega en un momento humano de verdad. A los conductores que hacen pausa los describen como 'muy amables'. A los que no, los describen como 'apresurados' — aunque tarden exactamente lo mismo.", tip:"Cuenta uno en tu cabeza. Y vete."},
    ]
  },
  {
    e:"🔥", t:"Manejando situaciones difíciles", sub:"Qué decir cuando las cosas salen mal", free:false,
    secs:[
      {h:"Siente. Sintieron. Encontré.", body:"La fórmula de 3 pasos para cualquier cliente frustrado.\n1. 'Entiendo cómo te sientes.' — lo escuchaste.\n2. 'Muchos clientes se sienten igual.' — su frustración es normal.\n3. 'Lo que he encontrado es…' — dale el siguiente paso.\nEjemplo para una entrega tarde: 'Entiendo perfectamente cómo te sientes — esperar es frustrante. Muchos clientes se sienten igual después de una larga espera. Lo que he encontrado es que un mensaje rápido a soporte normalmente lo resuelve rápido.' No estás admitiendo culpa. Estás reconociendo el sentimiento.", tip:"Siente. Sintieron. Encontré. Tres pasos. Funciona siempre."},
      {h:"Gana con calma, no discutiendo", body:"El enojo te acelera. Resístelo. Baja el ritmo, baja la voz, respira. La calma es contagiosa — igual que el enojo. No puedes ganarle una discusión a un cliente enojado. Pero sí puedes superarlo en calma. No interrumpas. No enumeres razones por las que no fue tu culpa. La mayoría de la gente sigue tu ejemplo en 30 segundos.", tip:"¿A la defensiva? Habla más lento y más bajo — no más rápido y más fuerte."},
      {h:"Redirige, no discutas", body:"A veces un cliente insiste en que pasó algo que tú sabes que no pasó. No puedes decirle que está equivocado — esa es una pelea que no puedes ganar. Mejor redirígelo a soporte. 'Lamento mucho escuchar eso — contacta directamente al soporte de [platform]. Ellos lidian con esto todo el tiempo y lo resuelven rápido.' No estás admitiendo culpa. No estás discutiendo. Lo estás señalando hacia la solución más rápida.", tip:"Termina la llamada con calma y un camino a seguir. No intentes ganar la discusión."},
    ]
  },
  {
    e:"💰", t:"La ciencia de las propinas", sub:"Por qué la gente da propina — y cómo lograrlo", free:false,
    secs:[
      {h:"Dos manos = más propinas", body:"La investigación sobre servicio muestra que breves momentos de intercambio físico real aumentan las propinas. No puedes crear contacto extra en la puerta de alguien — pero una presentación de la bolsa con dos manos es la versión para entregas. Dos manos, a la altura del pecho, de frente a ellos. Crea un intercambio en vez de una entrega. Los clientes sienten la diferencia sin saber por qué.", tip:"Dos manos siempre. No es la bolsa — es el momento."},
      {h:"Empatía, no quejas", body:"Los estudios muestran que mencionar brevemente el clima — con empatía, no quejándose — aumenta las propinas. '¡Me moví rápido para traértelo — qué frío esta noche!' La empatía gana propinas. Las quejas piden lástima. Son cosas distintas. La clave: una frase cálida, sin quejarse.", tip:"Una frase. Cálida, sin quejas."},
      {h:"Mencionarlo es el regalo", body:"Los regalos inesperados activan la reciprocidad — la gente siente el impulso de devolver algo. Servilletas extra, bebidas perfectamente verticales, un mensaje cálido de confirmación — todo son regalos. El truco: solo cuentan si los mencionas en voz alta. '¡Te agarré unas servilletas extra por si las necesitas!' Los regalos no mencionados son invisibles. Los regalos mencionados pagan propinas.", tip:"Mencionarlo es el regalo. Dilo en voz alta."},
      {h:"Confirma la promesa de la propina anticipada", body:"Muchas plataformas dejan que los clientes den propina antes de la entrega. Esa propina es una apuesta por ti. Tu trabajo es confirmar la apuesta. Una entrega cálida y una foto limpia casi nunca hacen que reduzcan la propina. Una entrega descuidada a veces sí. Cada entrega confirma o rompe la promesa que el cliente hizo al dar propina.", tip:"Cada entrega confirma o rompe la promesa de la propina anticipada."},
    ]
  },
  {
    e:"📋", t:"Guiones de recuperación", sub:"Exactamente qué decir cuando hay un problema", free:false,
    secs:[
      {h:"Comida fría → redirige a soporte", body:"La comida fría casi siempre es culpa del restaurante — pero decirlo suena a excusa. No lo digas. En vez de eso: 'Lamento mucho eso. Yo contactaría al soporte de [platform] — ellos toman en serio los problemas de temperatura y lo resuelven rápido.' No estás asumiendo culpa. Estás señalando la solución. Eso es lo que realmente quieren.", tip:"Nunca culpes al restaurante en voz alta. Redirige a soporte siempre."},
      {h:"Nunca digas que revisaste la bolsa", body:"'Revisé la bolsa y todo estaba ahí' es una discusión que no se puede ganar. No lo digas — aunque lo creas. En vez de eso: 'Lo siento mucho — recogí la bolsa sellada del restaurante. La solución más rápida es el soporte de [platform].' Deja que la plataforma lo maneje. Para eso están. Tu calificación se mantiene limpia.", tip:"Nunca digas que revisaste. Siempre redirige a soporte."},
      {h:"Reconócelo. Una frase. Basta.", body:"Si el error fue tuyo — dirección equivocada, tardaste mucho, se te cayó algo — reconócelo por completo y brevemente. 'Fue completamente mi culpa y lo siento.' Y para. Sin 'pero el tráfico'. Sin 'la app estaba fallando'. Los clientes califican más alto después de un error manejado con total responsabilidad que después de una entrega perfecta. Reconócelo. Lo respetan.", tip:"Reconócelo. Una frase. Basta. Sin excusas."},
    ]
  },
  {
    e:"🗺️", t:"Conoce tu entrega", sub:"Diferentes situaciones necesitan diferentes enfoques", free:false,
    secs:[
      {h:"Rapidez y calidez, o cuidado y comunicación", body:"Pedidos de restaurante → rapidez y calidez. Comida caliente, entrega rápida, saludo breve. Pedidos de mercado → cuidado y comunicación. A los clientes les importa la calidad de los productos frescos, el manejo cuidadoso, mensajes sobre cualquier agotado. No hagas mercado como restaurante. No hagas restaurante como mercado.", tip:"Restaurante: rápido y cálido. Mercado: cuidadoso y comunicativo."},
      {h:"Apartamentos: escribe primero, siempre", body:"Las casas son fáciles: camina a la puerta, toca una vez, da un paso atrás. Los apartamentos son diferentes. Siempre escribe primero — '¡Hola! Estoy en la entrada principal — ¿me puedes abrir?' El cliente no tiene idea de que estás afuera. La comunicación rápida le gana a lo lento y silencioso siempre.", tip:"Regla de apartamentos: escribe primero, siempre. No asumas — comunica."},
      {h:"Lee el reloj como una instrucción", body:"Almuerzo (11–2): pausa del trabajo. Sé rápido y breve. Cena (5–9): la calidez gana — 'que disfrutes tu comida' rinde más aquí que en ningún lado. De noche (10–2): en silencio, sin toques fuertes, entrega limpia. Mañana (5–10): con ánimo — la vara está baja, la amabilidad destaca. El reloj te dice exactamente cómo ajustarte antes de llegar.", tip:"La hora del día = cómo actuar. Lee el reloj como instrucciones."},
    ]
  },
  {
    e:"🏆", t:"Mantén tu nivel", sub:"Cómo seguir ganando más a largo plazo", free:true,
    secs:[
      {h:"Cada puerta = un cliente nuevo", body:"En un trabajo normal, un mal día no termina tu carrera. En las entregas por app, cada pedido se califica por separado — por alguien que no sabe nada de tu última entrega. Esa es la buena noticia: una mala entrega no tiene que afectar la siguiente. A menos que cargues la frustración contigo. La habilidad que mejor paga no es manejar. Es empezar de cero cada vez.", tip:"Este cliente nunca te ha conocido. No lleves la frustración a su puerta."},
      {h:"Respira. Reinicia. Elige una.", body:"Después de una entrega difícil, toma 60 segundos antes de la siguiente.\n1. Respira — ya pasó. No puedes cambiarlo.\n2. Recuerda que el próximo cliente es una persona completamente distinta.\n3. Elige una cosa pequeña para hacer bien — solo una.\nEse es el reinicio. Los conductores que hacen esto son más constantes, califican más alto y ganan más con el tiempo.", tip:"Respira. Reinicia. Elige una cosa para la próxima entrega."},
      {h:"Sigue tendencias, no calificaciones aisladas", body:"El agotamiento llega sin avisar. Señales de alerta: dejar de enviar los mensajes proactivos, entregas de dejar-y-correr, enojo por calificaciones bajas, sin contacto visual en la puerta. La solución normalmente no es renunciar — es ajustar. Menos horas. Otra zona. Sigue tu promedio semanal de propinas en vez de cada calificación individual. Las tendencias motivan. Los datos aislados solo duelen.", tip:"Sigue tu promedio semanal de propinas. No calificaciones individuales."},
    ]
  },
  {
    e:"🍔", t:"En el restaurante", sub:"Manejando problemas al recoger que protegen tu calificación", free:false,
    secs:[
      {h:"Fotografía el recibo", body:"En el momento en que recoges una bolsa sellada, es tuya. Verifica antes de llevártela.\n1. El número de pedido coincide con tu app.\n2. Cuenta los artículos si la bolsa está abierta.\n3. Revisa las bebidas — el artículo #1 que falta.\n4. Fotografía el ticket del pedido o el recibo.\nLa foto del recibo es tu prueba de lo que recogiste. 30 segundos. Elimina toda una categoría de quejas falsas.", tip:"Fotografía el recibo. Es tu prueba."},
      {h:"Lo que falta en el restaurante se queda en el restaurante", body:"¿Falta algo mientras aún estás en el restaurante? Para. No te vayas. 'A este pedido le falta [item] — ¿podemos agregarlo antes de que me lo lleve?' Si está agotado, pregunta qué sustituyeron y confirma que el cliente lo aprobó. En la puerta, dile al cliente claramente: 'El restaurante no tenía [item], lo sustituyeron con [X].' Entonces es su decisión, no la tuya. Nunca te vayas incompleto esperando que no se den cuenta.", tip:"Lo que falta en el restaurante se queda en el restaurante."},
      {h:"Espera en silencio. Comunica en voz alta.", body:"¿El pedido no está listo? No te quedes ahí frustrado.\n1. Pregunta al personal: '¿A qué hora vuelvo a preguntar?'\n2. Hazte a un lado. Estar encima los hace más lentos.\n3. Envíale un mensaje al cliente: 'Aún esperando la preparación — debería estar listo en unos [X] min.'\n15 segundos salvan tu calificación. Un cliente sin información imagina lo peor. Un cliente informado se mantiene tranquilo. ¿Más de 10 min tarde? Vuelve a escribir y toma captura de pantalla de la hora como prueba.", tip:"Hazte a un lado. Escribe al cliente. Captura la espera."},
      {h:"El daño detectado al recoger se queda al recoger", body:"Inspecciona la bolsa antes de irte. Bebidas: ¿algo mojado? Artículos frágiles: ¿algo aplastado? ¿Ves daño? No te lo lleves. 'Esto se ve dañado — ¿podemos cambiarlo?' No aceptes un descuento ni un 'lo arreglamos después'. Si no lo detectas hasta la puerta, fotógrafalo, muéstraselo al cliente y contacta a soporte. Los clientes recuerdan al conductor que detectó el problema y lo resolvió.", tip:"El daño al recoger se queda al recoger. Nunca lo transportes esperando que no se den cuenta."},
    ]
  },
];

var MSG_CATS_ES = [
  {e:"📲",t:"Lo que decir cuando llegas",sub:"Mensajes que te ganan calificaciones de 5 estrellas",secs:[
    {h:"Llegada estándar",msg:"¡Hola! Llegando ahora con tu pedido de [restaurante]. Lo dejaré en tu puerta. ¡Que lo disfrutes! 😊",w:"Establece expectativas antes de que abran la app. Los clientes a menudo te califican antes de ver la comida.",hint:"Reemplaza [restaurante] con el nombre real del restaurante — ej. 'McDonald's' o 'Chipotle'."},
    {h:"A pocos minutos",msg:"¡Hola! Solo un aviso — estoy a unos 3-4 minutos con tu comida. ¡Hasta pronto!",w:"El aviso anticipado significa que te esperan en la puerta o están listos cuando llegas. También reduce tu tiempo de espera."},
    {h:"Edificio de apartamentos",msg:"¡Hola! Estoy en la entrada principal con tu pedido. ¿Puedes abrirme la puerta o bajar al lobby? ¡Gracias!",w:"Siempre envía un mensaje antes de llamar en apartamentos. La mayoría de personas responden en menos de 30 segundos cuando su comida está afuera."},
    {h:"Confirmación sin contacto",msg:"Tu pedido ha sido dejado en tu puerta. ¡Que lo disfrutes! 🍕",w:"Una confirmación rápida elimina casi por completo las quejas falsas de no entrega."},
    {h:"Oficina o negocio",msg:"¡Hola! Estoy abajo en [edificio] con tu pedido. ¡Puedo dejarlo en recepción o puedes bajar a buscarlo!",w:"Ofrecer opciones demuestra profesionalismo y te ahorra un viaje en vano.",hint:"Reemplaza [edificio] con el nombre de la empresa o edificio que aparece en la app."},
  ]},
  {e:"⏰",t:"Cuando llegas tarde",sub:"Cómo convertir una mala situación en 5 estrellas",secs:[
    {h:"El restaurante tarda demasiado",msg:"¡Hola! Tu pedido aún está siendo preparado en el restaurante. Estoy aquí y me dirigiré hacia ti en cuanto esté listo. ¡Gracias por tu paciencia!",w:"Los clientes que no reciben noticias asumen que te olvidaste de ellos. Un mensaje cambia eso completamente. 'Gracias por tu paciencia' reconoce al cliente — 'disculpa la espera' implica culpa por algo que no es tu error."},
    {h:"Atascado en tráfico",msg:"¡Hola! Llevo un poco de retraso por el tráfico. Voy en camino y llegaré lo antes posible — ¡gracias por tu paciencia!",w:"Nunca culpes a la app o al restaurante. Reconócelo brevemente y mantén una actitud positiva."},
    {h:"Retraso significativo",msg:"¡Hola! De verdad lamento el retraso de esta noche. Tengo [tráfico / larga espera en el restaurante] y estaré allí en aproximadamente [X] minutos. De verdad aprecio tu paciencia.",w:"Los retrasos más grandes necesitan un reconocimiento mayor. Sé directo y da un tiempo estimado real.",hint:"Reemplaza [tráfico / larga espera en el restaurante] con lo que realmente está pasando, y [X] con tus minutos estimados reales."},
    {h:"Seguimiento tras el retraso",msg:"Acabo de dejar tu pedido — de verdad lamento la espera de esta noche. ¡Espero que todo esté delicioso! Que tengas una buena noche.",w:"Casi ningún repartidor hace esto. Frecuentemente convierte una calificación de 3 estrellas en 5 estrellas."},
  ]},
  {e:"🚨",t:"Cuando algo sale mal",sub:"Mensajes que protegen tu calificación",secs:[
    {h:"No encuentro la dirección",msg:"¡Hola! Tengo un poco de dificultad encontrándote. Estoy cerca de [referencia]. ¿Puedes ayudarme con indicaciones o un código de acceso?",w:"Siempre envía un mensaje antes de llamar. Dales algo específico con lo que trabajar.",hint:"Reemplaza [referencia] con algo que puedas ver cerca — un nombre de tienda, señal de calle o edificio."},
    {h:"Necesito un código de acceso",msg:"¡Hola! Estoy en la entrada pero necesito un código para entrar. ¿Me lo puedes enviar? ¡Estoy aquí!",w:"La gente responde en segundos cuando su comida está justo afuera."},
    {h:"Nadie abre la puerta",msg:"¡Hola! Estoy en tu puerta y toqué. Esperaré un par de minutos — si no recibo respuesta puede que necesite dejarla en la puerta. ¡Solo quiero asegurarme de que la recibas!",w:"Documenta tu intento y les da la oportunidad de responder."},
    {h:"Entrega segura con foto",msg:"Tu pedido ha sido dejado en tu puerta. Tomé una foto como confirmación. ¡Que lo disfrutes!",w:"Mencionar la foto de forma casual te protege de quejas falsas."},
    {h:"Complejo de apartamentos grande",msg:"¡Hola! Estoy en el estacionamiento de [nombre del complejo] pero tengo dificultad encontrando tu unidad. ¿Puedes ayudarme — qué número de edificio, entrada o escalera? ¡Ya casi llego!",w:"Pedir una referencia específica te da una respuesta útil rápidamente.",hint:"Reemplaza [nombre del complejo] con el nombre del complejo de apartamentos de la dirección de entrega."},
  ]},
  {e:"⭐",t:"Cómo obtener mejores propinas y calificaciones",sub:"Qué decir — y qué nunca decir",secs:[
    {h:"Despedida natural que genera propinas",msg:"¡Que disfrutes tu comida! Si algo llegara a pasar no dudes en contactarme por la app. ¡Que tengas una excelente noche! 😊",w:"Te posiciona como alguien que se preocupa — sin pedir nada a cambio."},
    {h:"Cuando fuiste más allá",msg:"¡Gracias por el pedido! Me aseguré de mantener todo derecho y caliente en el camino. ¡Espero que lo disfrutes hasta el último bocado!",w:"Señalar tu cuidado hace que miren la bolsa con aprecio, no con sospecha."},
    {h:"Cuando agregaste algo extra",msg:"¡Hola! La bolsa tenía pocas servilletas así que agarré unas extra. Todo lo demás está bien — ¡que lo disfrutes!",w:"Si no lo mencionas puede que no lo noten. Si lo dices, es memorable."},
    {h:"Lo que NUNCA debes decir",caution:true,msg:"¡Por favor dame 5 estrellas! / De verdad necesito una buena calificación esta semana. / ¿Podrías agregar una propina? / Este pedido fue muy lejos.",w:"Pedir calificaciones o propinas va en contra de las reglas de la plataforma y hace sentir incómodos a los clientes. Casi siempre resulta en una peor calificación."},
  ]},
  {e:"🏢",t:"Situaciones de entrega difíciles",sub:"Mensajes palabra por palabra para las difíciles",secs:[
    {h:"Entrega en hotel",msg:"¡Hola! Estoy en el lobby de [hotel] con tu pedido. La recepción no puede aceptar entregas — ¿podrías bajar? ¡Con gusto espero!",w:"Siempre anúnciate desde el lobby, no desde el piso de la habitación.",hint:"Reemplaza [hotel] con el nombre real del hotel."},
    {h:"Comunidad cerrada, sin código",msg:"¡Hola! Estoy en la entrada pero no recibí un código con el pedido. ¿Puedes enviarlo o abrirme? ¡Estoy aquí!",w:"No esperes. Envía un mensaje inmediatamente. Cada minuto en la entrada es tiempo perdido."},
    {h:"El cliente parece molesto en la puerta",msg:"Lo entiendo — llegué lo más rápido que pude. ¡Espero que el resto de tu noche mejore!",w:"Empatía, no disculpa. No sabes qué causó su molestia — puede que no tenga nada que ver contigo. 'Lo entiendo' reconoce su sentimiento sin admitir culpa. Breve, calmado, amable. Deséales bien y vete."},
  ]},
  {e:"🚙",t:"Lyft — Mensajes para pasajeros",sub:"Para recogidas, no-shows y situaciones difíciles",secs:[
    {h:"En camino a recogerte",msg:"¡Hola! En camino — a unos 2-3 minutos. Estaré en un [color y modelo del auto]. ¡Hasta pronto!",w:"Los pasajeros que saben qué auto buscar te encuentran más rápido, reduciendo tiempos de espera y cancelaciones.",hint:"Reemplaza [color y modelo del auto] con la descripción de tu auto — ej. 'Honda Accord plateado' o 'Toyota Camry blanco'."},
    {h:"En el punto de recogida — pasajero no visible",msg:"¡Hola! Estoy en tu punto de recogida. Estoy en un [color y modelo del auto] — ¡avísame si necesitas que avance un poco!",w:"Envía esto en lugar de esperar en silencio o cancelar temprano. La mayoría de pasajeros responden en menos de un minuto.",hint:"Reemplaza [color y modelo del auto] con la descripción de tu auto — ej. 'Honda Accord plateado'."},
    {h:"Ligero retraso en camino a la recogida",msg:"¡Hola! Llegaré unos [X] minutos tarde — [tráfico / desvío]. ¡Voy en camino y casi llego!",w:"Un aviso honesto casi siempre previene una cancelación. Los pasajeros que saben que vas rara vez se van.",hint:"Reemplaza [X] con tu retraso estimado real en minutos, y [tráfico / desvío] con la razón real."},
    {h:"El pasajero dejó algo en tu auto",msg:"¡Hola! Parece que dejaste [objeto] en mi auto. Lo reporté a través de la app de Lyft — puedes reclamarlo en tu historial de viajes en Objetos Perdidos. ¡Espero que lo recuperes!",w:"Siempre reporta los objetos perdidos a través del sistema oficial de Lyft — nunca arregles devoluciones directamente fuera de la app.",hint:"Reemplaza [objeto] con lo que dejaron — ej. 'tu teléfono' o 'una mochila'."},
    {h:"El pasajero parece molesto durante el viaje",msg:"Lamento que estés pasando por un momento difícil. Déjame llevarte lo más cómodamente posible.",w:"Breve, tranquilo, genuino. No preguntes qué pasa, no te sobreexpliques. Solo reconoce y vuelve a enfocarte en el manejo. La mayoría se calmarán en 60 segundos."},
  ]},
{e:"🚗",t:"Uber — Mensajes de viaje",sub:"Para recogidas, ausencias y situaciones difíciles con pasajeros",secs:[
    {h:"En camino a tu recogida",msg:"¡Hola! En camino — a unos 2-3 minutos. Estaré en un [car color and model]. ¡Nos vemos pronto!",w:"Los pasajeros que saben qué auto buscar te encuentran más rápido. Reduce el tiempo de espera y las cancelaciones antes de que llegues.",hint:"Reemplaza [car color and model] con la descripción de tu auto — ej. 'silver Honda Accord' o 'black Kia Soul'."},
    {h:"En la recogida — pasajero no visible",msg:"¡Hola! Ya estoy en tu punto de recogida. Estoy en un [car color and model] — ¡avísame si necesitas que avance o si ya vienes en camino!",w:"Envía esto en lugar de esperar en silencio o cancelar antes de tiempo. La mayoría de los pasajeros responde en menos de un minuto cuando saben que estás ahí.",hint:"Reemplaza [car color and model] con la descripción de tu auto — ej. 'silver Honda Accord'."},
    {h:"Pequeño retraso camino a la recogida",msg:"¡Hola! Llevo unos [X] minutos de retraso — [traffic / slight detour]. ¡Sigo en camino y casi llego!",w:"Un aviso honesto casi siempre evita una cancelación. Los pasajeros que saben que vienes rara vez se van.",hint:"Reemplaza [X] con tu retraso estimado real en minutos, y [traffic / slight detour] con la razón real."},
    {h:"El pasajero dejó algo en tu auto",msg:"¡Hola! Parece que dejaste [item] en mi auto. Ya lo reporté por la app de Uber — puedes reclamarlo en tu historial de viajes bajo Objetos Perdidos. ¡Espero que lo recuperes!",w:"Siempre repórtalo por el sistema oficial de objetos perdidos de Uber — nunca arregles una devolución directa fuera de la app. Esto te protege a ti y al pasajero.",hint:"Reemplaza [item] con lo que dejaron — ej. 'your phone' o 'a jacket'."},
    {h:"El pasajero parece molesto durante el viaje",msg:"Lamento que estés pasando un mal rato. Te llevaré de la forma más tranquila posible.",w:"Corto, calmado, genuino. No preguntes qué pasa, no sobreexpliques. Solo reconoce y enfócate en manejar. La mayoría de los pasajeros se calma en 60 segundos."},
  ]},
{e:"🔥",t:"Guiones de desescalada",sub:"Respuestas palabra por palabra cuando una situación se pone difícil",secs:[
    {h:"Cliente amenazando con mala calificación",msg:"Lamento escuchar que no estás contento. Genuinamente hice lo mejor en esta entrega. Si hay un problema con el pedido en sí, soporte puede resolverlo — son el camino más rápido a una solución.",w:"No discute, no ruega. Reconoce tu esfuerzo, redirige al canal que realmente puede arreglarlo. Te mantiene fuera de un ida y vuelta que no terminará bien."},
    {h:"Cliente enojado en la puerta",msg:"Te entiendo — lamento la espera. Llegué lo más rápido que pude. Espero que la comida lo compense. Que tengas buena noche.",w:"Cuatro frases. Reconoce, contexto breve, calidez, sal. No estás debatiendo el tiempo de espera — estás terminando la interacción. Corto y listo es mejor que largo y correcto."},
    {h:"Cliente insiste en que el pedido está mal (bolsa sellada)",msg:"Recogí la bolsa sellada directamente del restaurante — todo fue empacado por ellos. Para un artículo faltante o equivocado, soporte puede emitir un crédito o reemplazo rápido. Yo lo haría por la app — usualmente lo resuelven rápido.",w:"Factual y redirige. No eres responsable de lo que el restaurante empacó en una bolsa sellada. Esto enmarca las cosas correctamente sin sonar defensivo."},
    {h:"Pasajero molesto por la ruta",msg:"Te entiendo — lo tendré en cuenta. Te llevaré de la forma más tranquila posible de aquí en adelante.",w:"Reconoce una vez, gira hacia adelante. No estás aceptando que te equivocaste. No te estás explicando. Un reconocimiento y una frase mirando adelante lo terminan."},
    {h:"Cliente dice que te fuiste sin que supiera",msg:"Hola — llegué a [address] a las [time] y esperé [X] minutos. Envié un mensaje por la app antes de completar la entrega. Lamento que no nos hayamos encontrado — soporte debería poder revisar el registro de entrega.",w:"Factual, documentado, sin disculpa por haber completado correctamente. Tienes una marca de tiempo, un registro de mensajes y una foto. Expón los hechos con calma y dirígelos a soporte."},
    {h:"Cuando necesitas terminar un viaje antes por seguridad",msg:"Voy a necesitar terminar este viaje aquí. Espero que llegues a tu destino con bien.",w:"Corto, calmado, final. No debes una explicación. Si te sientes inseguro, termínalo — esa siempre es la decisión correcta. Repórtalo por la app inmediatamente después con detalles específicos de lo que pasó."},
  ]}
];

var PLATFORMS_DEFEND_ES = [
  {id:"doordash",  label:"DoorDash",  color:"#FF3008", e:"🔴"},
  {id:"ubereats",  label:"Uber Eats", color:"#06C167", e:"🟢"},
  {id:"spark",     label:"Spark",     color:"#0071CE", e:"🔵"},
  {id:"instacart", label:"Instacart", color:"#43B02A", e:"🟩"},
  {id:"lyft",      label:"Lyft",      color:"#FF00BF", e:"🚙"},
  {id:"amazonflex", label:"Flex",      color:"#FF9900", e:"📦"},
  {id:"uber",      label:"Uber",      color:"#1D1D1D", e:"🚗"},
  {id:"gopuff",    label:"GoPuff",    color:"#4338CA", e:"🟣"},
];

var PLATFORM_HABITS_ES = {
  doordash:[
    {e:"📸",t:"Foto en cada entrega",why:"Tu foto es tu protección número 1. El soporte de DoorDash la compara con tu GPS. Una foto clara que muestre la comida en la puerta con la dirección visible gana casi todos los casos falsos de no entrega. Sin ella, no tienes caso.",urgent:true},
    {e:"💬",t:"Mensaje dentro de la app en cada pedido",why:"Tu historial de mensajes dentro de la app tiene fecha y hora, y el soporte de Dasher puede verlo. Cuando un cliente dice que nunca te comunicaste, tu conversación demuestra lo contrario. Un mensaje por entrega te protege por completo.",urgent:true},
    {e:"📍",t:"GPS activo durante todo el turno",why:"DoorDash registra tu ubicación durante toda la entrega. Si un cliente reporta no entrega, el soporte revisa tu recorrido GPS para confirmar que estuviste en su dirección. Sin GPS, tu palabra no vale nada.",urgent:true},
    {e:"🖼️",t:"Captura de pantalla de la confirmación de entrega",why:"Cuando la app muestre la entrega confirmada, toma una captura antes de seguir. Este es el registro con fecha y hora de la propia plataforma de que el pedido se completó — aparte de tu foto, e igual de importante en una disputa."},
    {e:"💎",t:"Dar lo mejor siempre rinde frutos",why:"Los repartidores que manejan cada bolsa con cuidado y tratan cada puerta como si importara construyen un historial que se acumula. Mejores calificaciones → mejores propinas → mejores pedidos. El servicio de primera también es la estrategia más rentable."},
    {e:"📋",t:"Anota el número de pedido en cualquier entrega con problemas",why:"Si un restaurante se retrasa, un cliente parece molesto o algo se siente raro — anota rápido el número de pedido de DoorDash. Es lo que usan los agentes para buscar tu registro. Hace cualquier apelación mucho más fuerte."},
  ],
  ubereats:[
    {e:"📸",t:"Foto en cada entrega",why:"Uber Eats exige una foto en las entregas sin contacto. Esa foto tiene fecha, hora y ubicación, y se guarda en el sistema de Uber. En cualquier disputa, el soporte la revisa de inmediato. Si no tomaste una, no tienes evidencia.",urgent:true},
    {e:"💬",t:"Mensajes solo dentro de la app — nunca por SMS",why:"El soporte de Uber solo puede ver tu historial de mensajes dentro de la app, no los SMS. Siempre escribe a través de la app de Uber Eats para que cada comunicación quede registrada. Los mensajes dentro de la app son tu prueba si un cliente dice que lo ignoraste.",urgent:true},
    {e:"📍",t:"GPS activo durante todo el turno",why:"El sistema de disputas de Uber depende de los datos GPS del viaje más que ninguna otra plataforma. Los agentes revisan tu recorrido en cada queja de entrega. Si el GPS estaba apagado, no pueden verificar y normalmente le dan la razón al cliente.",urgent:true},
    {e:"🆔",t:"Captura tu ID de viaje en entregas con problemas",why:"Uber identifica cada entrega con un ID de viaje. En cualquier apelación al soporte debes incluirlo — sin el ID de viaje, los agentes no pueden encontrar tu registro. Toma captura de la pantalla del resumen del viaje después de cualquier cosa que se haya sentido rara."},
    {e:"⭐",t:"Tu calificación decide qué viajes ves",why:"Uber muestra los viajes mejor pagados a los conductores con mejor calificación. Por debajo de 4.7 en Uber Eats empieza a bajar la calidad de tus viajes. La política de Uber permite eliminar calificaciones causadas por errores del restaurante o factores fuera de tu control — pídela."},
    {e:"🔄",t:"Documenta las esperas largas en el restaurante con un mensaje",why:"¿Más de 10 minutos esperando en un restaurante? Envía al cliente una nota dentro de la app sobre el retraso. Crea un registro con fecha y hora de que la espera fue culpa del restaurante, no tuya — lo cual importa si te califican bajo por el tiempo."},
  ],
  spark:[
    {e:"📸",t:"Foto en cada entrega",why:"Walmart Spark exige una foto en cada pedido. Es tu prueba de entrega y tu protección contra reclamos falsos. Foto clara mostrando las bolsas en la puerta con el número de la casa visible. Sin ella, el soporte le da la razón al cliente.",urgent:true},
    {e:"📦",t:"Verifica el pedido completo en la tienda",why:"Los conductores de Spark son responsables de recoger los artículos. Si algo falta, los clientes pueden quejarse de ti. Antes de salir de la tienda: verifica todos los artículos, marca lo no disponible en la app, fotografía el carrito en pedidos grandes.",urgent:true},
    {e:"💬",t:"Mensaje dentro de la app sobre cada sustitución",why:"Cuando un artículo no está disponible y lo sustituyes, escribe al cliente a través de la app de Spark antes de salir de la tienda. Esto demuestra que seguiste el proceso de sustitución. Los agentes revisan tu historial de mensajes en cada disputa.",urgent:true},
    {e:"📍",t:"GPS activo durante todo el turno",why:"Spark usa el GPS para verificar la ubicación y el tiempo de entrega. Si el GPS confirma que estuviste en la dirección, esa es tu evidencia más fuerte. Si estaba apagado, no tienes forma de probar que la entrega ocurrió."},
    {e:"🧾",t:"Captura del resumen de entrega",why:"Después de completar un pedido, la app de Spark muestra un resumen de lo entregado, incluyendo sustituciones y artículos no disponibles. Toma captura siempre. Si un cliente dice que faltaron artículos, este es el registro del propio sistema."},
    {e:"⭐",t:"La puntualidad se califica por separado",why:"Spark registra tu tasa de entregas a tiempo por separado de tu calificación de cliente. Ambas afectan tu acceso a mejores batches. ¿Un retraso en la tienda te hizo llegar tarde? Escribe al cliente y anota la espera — eso te da base para disputar una marca de retraso."},
  ],
  instacart:[
    {e:"📸",t:"Foto en cada entrega",why:"Instacart exige una foto de entrega y la usa en cada disputa de no entrega. Debe mostrar los artículos en la puerta con la dirección o el número de la casa visible. El soporte revisa esto primero. Sin ella, no puedes ganar ningún caso de no entrega.",urgent:true},
    {e:"🛒",t:"Escanea cada artículo en la tienda",why:"Instacart registra qué artículos escaneaste. Si un cliente dice que faltó un artículo y tú lo escaneaste, ese registro de escaneo es tu prueba. Si no lo escaneaste, el sistema no tiene registro de que lo tenías. Cada artículo, cada vez.",urgent:true},
    {e:"💬",t:"Mensaje dentro de la app sobre cada reemplazo",why:"Cuando un artículo está agotado y lo reemplazas, escribe al cliente a través de la app de Instacart antes de pagar. Si disputan el reemplazo después, tu mensaje demuestra que seguiste el proceso correcto.",urgent:true},
    {e:"📋",t:"Anota tu ID de batch en cualquier pedido con problemas",why:"El soporte de Instacart identifica los pedidos por ID de batch. En cualquier entrega donde algo salga mal, anota o captura el ID del batch de inmediato. No puedes presentar una apelación efectiva sin él."},
    {e:"⭐",t:"4.7 es la calificación que debes proteger",why:"Los shoppers por debajo de 4.7 ven menos batches y peor pagados. Algunos batches bien pagados solo están disponibles arriba de 4.8. Es posible eliminar calificaciones por quejas causadas por artículos agotados, errores de la tienda o fallas de la app — pero tienes que pedirlo."},
    {e:"🔄",t:"Documenta a los clientes difíciles antes de que se quejen",why:"¿Cliente grosero o con exigencias irrazonables? Anótalo en los comentarios de la app de Instacart de inmediato. Crea un registro antes de que se presente cualquier disputa. Le indica al soporte que el cliente tiene historial si después presenta una queja falsa."},
  ],
  amazonflex:[
    {e:"📸",t:"Foto en cada entrega",why:"Flex depende mucho de las fotos de entrega. Foto clara y bien iluminada mostrando el paquete en su ubicación final (porche, buzón, etc.). Esta es tu protección número 1 contra quejas de 'nunca recibido'.",urgent:true},
    {e:"📍",t:"GPS activo durante todo el turno",why:"La plataforma registra tu ruta GPS. En cualquier disputa, el soporte compara tu recorrido con la dirección de entrega y la hora. GPS apagado = sin prueba.",urgent:true},
    {e:"🔢",t:"Escanea una dirección a la vez en paradas con varios paquetes",why:"Esto obliga a la app a pedirte una foto en cada parada. Saltarte esto es una razón común por la que penalizan a los conductores por paquetes faltantes.",urgent:true},
    {e:"🖼️",t:"Captura de la confirmación de entrega",why:"Después de marcar como entregado, captura la pantalla de confirmación de inmediato. Muestra la hora exacta y los IDs de TBA/paquete — tu prueba de que completaste la entrega si hay disputa."},
    {e:"🔄",t:"Devuelve los no entregables con el código de motivo correcto",why:"Usa siempre el código de motivo de no entregable de la app en el lugar si no puedes entregar. Devuélvelos a la estación el mismo día o antes de las 10am del día siguiente."},
    {e:"📋",t:"Anota el ID del bloque y el TBA en entregas con problemas",why:"El soporte identifica tu bloque por el ID del bloque y los paquetes individuales por el TBA. Tómales captura o anótalos de inmediato si algo se siente raro — no puedes apelar sin ellos."},
  ],
  lyft:[
    {e:"🪪",t:"Confirma primero el nombre del pasajero",why:"Tu protección de seguridad número 1 y la política oficial de Lyft. Antes de desbloquear, pregunta '¿Cómo te llamas?' y espera a que te lo digan. Nunca digas el nombre primero — si alguien se sube al auto equivocado, podrían responsabilizarte.",urgent:true},
    {e:"📋",t:"Captura el ID del viaje si algo se siente raro",why:"Lyft usa los IDs de viaje para buscar tu registro en cualquier disputa. Si un pasajero es difícil o se queja, el ID del viaje es como el soporte encuentra tu viaje. Toma captura del resumen del viaje después de cualquier viaje incómodo — antes de que la app se reinicie.",urgent:true},
    {e:"🔇",t:"Deja que el pasajero marque el tono",why:"Alrededor del 60% de los pasajeros de Lyft prefieren viajes tranquilos. Nunca empieces a hablar en cuanto suban. Dales 15–20 segundos. Ellos hablan primero → sigue su ejemplo. Se quedan callados → quédate callado. La conversación forzada es una de las principales causas de calificaciones bajas.",urgent:true},
    {e:"🚗",t:"Auto limpio. Cargador listo.",why:"La limpieza es el factor más mencionado en las calificaciones de los pasajeros. Sin olores fuertes, interior ordenado, cargador de teléfono disponible (tanto iPhone como Android). Los pasajeros mencionan el cargador en reseñas positivas más que casi cualquier otro detalle."},
    {e:"⭐",t:"Califica al pasajero con 5 estrellas de inmediato",why:"Los pasajeros que ven que les diste 5 estrellas tienen muchas más probabilidades de devolverte 5 estrellas. Califica antes de que ellos tengan oportunidad. Activa una respuesta de reciprocidad. Los conductores que califican primero consistentemente ven calificaciones generales más altas."},
    {e:"🎵",t:"Pregunta antes de poner música — mantén el volumen bajo",why:"Nunca asumas que un pasajero quiere tu lista de reproducción. '¿Te molesta si pongo algo de música?' muestra respeto y casi siempre recibe un sí. Música alta, bajos fuertes o letras agresivas están entre las cinco principales causas de calificaciones de 3 estrellas. Ante la duda: silencio."},
  ],
  uber:[
    {e:"🪪",t:"Confirma primero el nombre del pasajero",why:"Pregunta '¿Cómo te llamas?' antes de desbloquear — nunca digas el nombre primero. Si alguien se sube al auto equivocado podrían responsabilizarte. Es la política oficial de Uber y tu protección legal en cada viaje.",urgent:true},
    {e:"📋",t:"Captura el ID del viaje si algo se siente raro",why:"Uber usa los IDs de viaje para encontrar tu registro en cualquier disputa. ¿Pasajero difícil o queja? El ID del viaje es como el soporte localiza el viaje. Toma captura del resumen del viaje inmediatamente después — antes de que la app se reinicie.",urgent:true},
    {e:"🔇",t:"Deja que el pasajero marque el tono",why:"Nunca empieces a hablar en cuanto suban. Dales 15–20 segundos. Ellos hablan primero → sigue su ejemplo. Se quedan callados → quédate callado y profesional. La conversación forzada con un pasajero que quiere silencio es una causa común de calificaciones bajas.",urgent:true},
    {e:"🚗",t:"Auto limpio. Cargador listo.",why:"La limpieza del auto es el factor más mencionado en las calificaciones de los pasajeros. Sin olores fuertes, interior ordenado, cargador de teléfono listo (iPhone y Android). Repón los cargadores regularmente — los pasajeros los mencionan más que casi cualquier otro detalle."},
    {e:"⭐",t:"Califica al pasajero con 5 estrellas de inmediato",why:"Los pasajeros que ven que les diste 5 estrellas tienen muchas más probabilidades de devolverte 5 estrellas. Califícalos antes de que ellos hayan tenido tiempo de calificarte. Los conductores que califican primero consistentemente ven calificaciones generales más altas."},
    {e:"📷",t:"Mantén una cámara de tablero activa",why:"La grabación de video dentro del auto de Uber está disponible en los 50 estados. Una cámara de tablero crea un registro para cualquier queja disputada. No evitará quejas falsas, pero te da evidencia documentada — y los pasajeros se comportan diferente cuando ven una."},
  ],
  gopuff:[
    {e:"📸",t:"Foto en cada entrega",why:"Tu foto es tu protección principal contra quejas falsas de no entrega. Foto clara mostrando los artículos y el número de la puerta o la dirección de la casa. El equipo de soporte de GoPuff revisa estas igual que todas las plataformas de entrega.",urgent:true},
    {e:"📦",t:"Verifica tu cantidad de pedidos en el centro",why:"Los pedidos de GoPuff vienen pre-empacados, pero hay errores. Antes de salir del centro, confirma que la cantidad de bolsas o artículos coincida con la app. Salir con un pedido equivocado o incompleto genera una queja de la que serás responsable.",urgent:true},
    {e:"📍",t:"GPS activo durante todo el turno",why:"GoPuff usa el GPS para confirmar tu ubicación y tiempo de entrega. Es tu documentación principal de que estuviste en la dirección y cuándo."},
    {e:"💬",t:"Mensaje dentro de la app ante cualquier problema",why:"Necesitas código de acceso, no encuentras la dirección, el cliente no responde — siempre escribe primero dentro de la app. Los mensajes documentados dentro de la app demuestran que hiciste un esfuerzo de buena fe, lo cual te protege en cualquier disputa."},
    {e:"🏃",t:"Mantén las entregas en movimiento",why:"La promesa central de GoPuff es la entrega rápida. Tiempos lentos de forma constante afectan tu posición. Solo acepta recorridos que puedas completar de forma realista dentro del tiempo esperado."},
  ],
};

var PLATFORM_APPEALS_ES = {
  doordash:[
    {e:"🚫",t:"Queja falsa de no entrega",urgency:"ALTA — Puede provocar desactivación",color:"#F43F5E",secs:[
      {h:"Disputa estándar de no entrega",timing:"Presenta dentro de 24 horas — el soporte revisa las quejas en lotes diarios",msg:"Hola, equipo de soporte de Dasher,\n\nEscribo para disputar una queja falsa de no entrega en el pedido de Dasher #[ORDER ID] del [DATE].\n\nEsta entrega se completó con éxito. Mi documentación:\n- Foto de entrega mostrando el pedido en [ADDRESS] con la puerta visible\n- Datos GPS confirmando mi ubicación en [ADDRESS] a las [TIME]\n- Marca de tiempo de confirmación de entrega en la app\n\nEl reclamo del cliente es inexacto. Solicito:\n1. Que esta queja se revise contra mi foto de entrega y mis datos GPS\n2. Que se revierta cualquier impacto negativo en mi tasa de finalización o mi posición como Dasher\n3. Que se revise la cuenta del cliente si esto es parte de un patrón\n\nGracias.",w:"'Dasher order #' es el término exacto que usa el soporte de DoorDash para buscar tu registro. Enumera cada evidencia como un punto separado — los agentes revisan cada una individualmente."},
      {h:"Misma dirección presentando múltiples quejas",timing:"Presenta en cuanto aparezca la segunda queja — los reportes de patrones reciben trato de escalación",msg:"Hola, equipo de soporte de Dasher,\n\nEscribo sobre un patrón de quejas falsas que creo viene de la misma ubicación.\n\nQuejas desde [ADDRESS]:\n- Pedido #[ORDER ID 1] del [DATE 1] — tengo prueba con foto de entrega\n- Pedido #[ORDER ID 2] del [DATE 2] — tengo prueba con foto de entrega\n\nCreo que este cliente está presentando repetidamente quejas falsas de no entrega para recibir reembolsos. Pido:\n1. Una revisión de todas las quejas de esta dirección contra mi evidencia de entrega\n2. Que esta dirección sea marcada en el sistema de DoorDash si se confirma un patrón\n3. Que se reviertan todos los efectos negativos en mi cuenta\n\nGracias.",w:"La frase 'patrón de quejas falsas' mueve tu ticket de una revisión individual a una investigación de fraude — se maneja de forma diferente y más seria."},
    ]},
    {e:"⭐",t:"Calificación injusta de un cliente",urgency:"MEDIA — Afecta el acceso a pedidos y Top Dasher",color:"#F5A623",secs:[
      {h:"Calificación causada por error del restaurante",timing:"Presenta después de que se publique la calificación — primero necesitas el número de pedido y la marca de tiempo",msg:"Hola, equipo de soporte de Dasher,\n\nSolicito la eliminación de una calificación de 1 estrella en el pedido #[ORDER ID] del [DATE].\n\nEsta calificación fue causada por un error del restaurante, no por mi desempeño:\n- Recibí una bolsa sellada del restaurante\n- No tuve forma de inspeccionar ni verificar el contenido\n- Mi entrega se completó correctamente y a tiempo\n\nLa política de DoorDash permite eliminar calificaciones que reflejan factores fuera del control del Dasher. Un error de empaque del restaurante cae directamente dentro de esa política. Mi calificación antes de esto era [X estrellas].\n\nPor favor revisen y eliminen esta calificación.\n\nGracias.",w:"'Factores fuera del control del Dasher' es el lenguaje exacto de la política interna de revisión de calificaciones de DoorDash. Usarlo le da al agente la justificación para aprobar la eliminación."},
      {h:"Calificación causada por tiempo de espera",timing:"Presenta dentro de las 48 horas de la entrega — el agente puede obtener las marcas de tiempo de espera del restaurante",msg:"Hola, equipo de soporte de Dasher,\n\nSolicito la eliminación de una calificación en el pedido #[ORDER ID] del [DATE].\n\nEl cliente dejó una calificación baja por el tiempo de entrega. Quiero señalar:\n- El pedido no estuvo listo en el restaurante hasta las [TIME]\n- Esperé [X] minutos en [restaurant name] antes de que el pedido estuviera listo\n- Entregué el pedido lo más rápido posible una vez que lo tuve\n\nLos retrasos en la preparación del restaurante están fuera del control de un Dasher según la política de DoorDash. Pido que se elimine esta calificación.\n\nGracias.",w:"DoorDash puede ver tu marca de tiempo de recogida frente a la hora en que el pedido estuvo listo. Nombrar el restaurante y el tiempo de espera le da al agente algo concreto que verificar."},
    ]},
    {e:"📉",t:"Tasa de finalización afectada injustamente",urgency:"ALTA — Impacta el nivel de Dasher y el acceso",color:"#F43F5E",secs:[
      {h:"Disputa de tasa de finalización",timing:"Presenta de inmediato — las caídas en la tasa de finalización afectan el acceso a pedidos al instante",msg:"Hola, equipo de soporte de Dasher,\n\nMi tasa de finalización se ha visto afectada negativamente por una queja en el pedido #[ORDER ID] del [DATE] que creo es incorrecta.\n\nPrueba de entrega exitosa:\n- Foto de entrega en [ADDRESS]\n- Datos GPS confirmando que estuve en la dirección a las [TIME]\n- Confirmación de entrega en la app\n\nMi tasa de finalización afecta directamente mi estatus como Dasher y mi acceso a los beneficios de Top Dasher y pedidos prioritarios. Pido que esta queja se revise y se revierta si la evidencia no la respalda.\n\nGracias.",w:"Nombrar 'estatus de Dasher', 'Top Dasher' y 'pedidos prioritarios' le muestra al agente que esto tiene un impacto financiero real en ti. Eso hace más probable que escalen una reversión."},
    ]},
    {e:"🔄",t:"Escalación — La apelación fue negada",urgency:"USAR DESPUÉS DE UNA PRIMERA NEGACIÓN",color:"#8B5CF6",secs:[
      {h:"Segunda apelación a un agente senior",timing:"Usa solo después de que tu primera apelación se cierre sin resolución — normalmente 2–3 días hábiles",msg:"Hola,\n\nDoy seguimiento a una solicitud anterior al soporte de Dasher sobre el pedido #[ORDER ID] del [DATE].\n\nMi apelación original no se resolvió a mi satisfacción. Solicito escalación a un especialista senior de cuentas Dasher porque:\n- Mi evidencia con foto de entrega no fue revisada correctamente\n- La queja contradice directamente mi recorrido GPS, la marca de tiempo de mi foto y mi registro de entrega en la app\n- Esta queja sigue impactando mi posición en la cuenta y mis ingresos\n\nHe sido un Dasher activo desde el [DATE] con un historial sólido. Pido una revisión senior exhaustiva.\n\nGracias.",w:"Pedir un 'especialista senior de cuentas Dasher' dirige tu ticket a un nivel diferente de revisión. La mayoría de los conductores no saben que pueden pedir esto. Mejora significativamente tus probabilidades."},
    ]},
  ],
  ubereats:[
    {e:"🚫",t:"Queja falsa de no entrega",urgency:"ALTA — Puede afectar tu cuenta",color:"#F43F5E",secs:[
      {h:"Disputa estándar de no entrega",timing:"Presenta dentro de 48 horas — la cola de revisión de Uber desprioriza las quejas más viejas",msg:"Hola, equipo de soporte de Uber Eats,\n\nEscribo para disputar una queja de no entrega en el viaje #[TRIP ID] del [DATE].\n\nCompleté esta entrega con éxito. Mi documentación:\n- Foto de entrega tomada en [ADDRESS] a las [TIME] — con ubicación y marca de tiempo\n- Datos GPS del viaje mostrando mi ubicación en la dirección de entrega\n- Registro de confirmación de entrega en la app\n\nSolicito:\n1. Que esta queja se revise contra mi foto y mis datos GPS del viaje\n2. Que se revierta cualquier efecto negativo en mi cuenta o tasa de finalización\n3. Una revisión del historial de quejas de este cliente si esto es un patrón\n\nGracias.",w:"El soporte de Uber trabaja con IDs de viaje — inclúyelo en la primera línea. 'Con ubicación y marca de tiempo' le dice al agente exactamente qué buscar en tu registro de fotos."},
      {h:"Entrega sin contacto — el cliente pidió no tocar",timing:"Presenta dentro de las 24 horas de que la queja aparezca en tu cuenta",msg:"Hola, equipo de soporte de Uber Eats,\n\nDisputo una queja en el viaje #[TRIP ID] del [DATE].\n\nEl cliente eligió entrega sin contacto. Esto fue lo que pasó:\n1. Llegué a [ADDRESS] a las [TIME]\n2. Dejé el pedido en la puerta como se me indicó — sin tocar ni timbrar según la preferencia del cliente\n3. Tomé y envié una foto de entrega\n4. La app confirmó la entrega y se envió una notificación\n\nSeguí las instrucciones exactas de entrega del cliente. Por favor revisen y eliminen esta queja.\n\nGracias.",w:"Uber Eats tiene una política específica que protege a los conductores que siguen instrucciones de entrega sin contacto. Enmarcar tu apelación en torno a 'la preferencia de entrega del cliente' invoca esa política directamente."},
    ]},
    {e:"⭐",t:"Calificación injusta",urgency:"MEDIA — Afecta la calidad de los viajes y las ganancias",color:"#F5A623",secs:[
      {h:"Calificación causada por un problema del restaurante",timing:"Presenta después de que la calificación se publique y aparezca en tu cuenta — no antes",msg:"Hola, equipo de soporte de Uber Eats,\n\nSolicito la eliminación de una calificación baja en el viaje #[TRIP ID] del [DATE].\n\nEsta calificación no refleja mi servicio. El cliente quedó insatisfecho con [missing item / food quality / wait time], lo cual fue causado por el restaurante, no por mí.\n\nRecogí un pedido sellado de [RESTAURANT NAME]. No tuve forma de inspeccionar ni modificar el contenido. Mi entrega se completó correctamente.\n\nLa política de Uber permite eliminar calificaciones causadas por factores fuera del control del socio repartidor. Mi calificación antes de esto era [X]. Por favor revisen y eliminen esta calificación.\n\nGracias.",w:"'Factores fuera del control del socio repartidor' refleja el lenguaje interno de revisión de Uber. Nombrar el restaurante específicamente le da al agente algo que verificar de forma independiente."},
    ]},
    {e:"🔄",t:"Escalación — Primera apelación negada",urgency:"USAR DESPUÉS DE UNA PRIMERA NEGACIÓN",color:"#8B5CF6",secs:[
      {h:"Escalar a un especialista senior",msg:"Hola,\n\nDoy seguimiento a una solicitud anterior sobre el viaje de Uber Eats #[TRIP ID] del [DATE].\n\nMi apelación inicial no se resolvió. Solicito escalación a un especialista senior de cuentas para una revisión completa porque:\n- Mi foto y mi evidencia GPS no fueron evaluadas correctamente\n- La queja contradice mi registro documentado de entrega\n- Esto sigue afectando mi cuenta y mis ingresos\n\nHe sido socio repartidor de Uber desde el [DATE] con un historial sólido. Pido una revisión exhaustiva.\n\nGracias.",w:"Pedir un 'especialista senior de cuentas' por ese nombre activa un cambio de ruta. La mayoría de los conductores se agotan con agentes de primer nivel — esta sola solicitud a menudo logra un resultado diferente."},
    ]},
  ],
  spark:[
    {e:"🚫",t:"Queja falsa de no entrega",urgency:"ALTA — Puede afectar tu posición como conductor de Spark",color:"#F43F5E",secs:[
      {h:"Disputa estándar de no entrega",msg:"Hola, equipo de soporte de Spark,\n\nEscribo para disputar una queja de no entrega en la entrega #[DELIVERY ID] del [DATE].\n\nEsta entrega se completó con éxito. Mi documentación:\n- Foto de entrega mostrando el pedido en [ADDRESS]\n- Datos GPS confirmando mi ubicación en la dirección de entrega a las [TIME]\n- Marca de tiempo de confirmación de entrega en la app\n\nSolicito:\n1. Que esta queja se revise contra mi foto de entrega y mi registro GPS\n2. Que se revierta cualquier impacto negativo en mi calificación o posición como conductor\n\nGracias.",w:"El soporte de Spark usa IDs de entrega para buscar registros. Inclúyelo en la primera línea. El equipo de Spark es más pequeño que el de DoorDash — da seguimiento después de 48 horas si no recibes respuesta."},
    ]},
    {e:"📦",t:"Disputa por artículo faltante o sustituido",urgency:"ALTA — Queja común específica de Spark",color:"#F43F5E",secs:[
      {h:"El artículo estaba agotado — seguiste el protocolo",msg:"Hola, equipo de soporte de Spark,\n\nEscribo para disputar una queja sobre un artículo faltante en la entrega #[DELIVERY ID] del [DATE].\n\nEl artículo [ITEM NAME] no estaba disponible en la tienda Walmart. Lo manejé correctamente:\n- Marqué el artículo como no disponible en la app de Spark\n- Seleccioné una sustitución aprobada / notifiqué al cliente sobre la no disponibilidad\n- Escribí al cliente a través de la app antes de pagar\n\nSeguí el protocolo de agotados de Spark al pie de la letra. Por favor revisen mis acciones dentro de la app para este batch y eliminen esta queja.\n\nGracias.",w:"Los agentes de Spark pueden ver exactamente lo que hiciste en la app — cuándo marcaste artículos como no disponibles, cuándo escribiste al cliente, cuándo pagaste. Esta apelación los dirige directamente a ese registro."},
    ]},
    {e:"🔄",t:"Escalación — La apelación fue negada",urgency:"USAR DESPUÉS DE UNA PRIMERA NEGACIÓN",color:"#8B5CF6",secs:[
      {h:"Escalar a revisión senior",msg:"Hola,\n\nDoy seguimiento a una solicitud anterior al soporte de Spark sobre la entrega #[DELIVERY ID] del [DATE].\n\nMi solicitud inicial fue negada. Solicito una revisión senior porque:\n- Mi foto de entrega y mi registro GPS no fueron evaluados correctamente\n- Mis acciones dentro de la app para este batch no fueron revisadas contra la queja\n- Esta queja está afectando injustamente mi calificación como conductor y mi acceso a batches\n\nHe sido conductor de Spark desde el [DATE] con un historial positivo. Pido una revisión completa.\n\nGracias.",w:"Dar seguimiento con una solicitud de revisión senior — y citar tu antigüedad — a menudo rompe el ciclo de negaciones de primer nivel."},
    ]},
  ],
  instacart:[
    {e:"🚫",t:"Queja falsa de no entrega",urgency:"ALTA — Puede afectar tu acceso como Shopper",color:"#F43F5E",secs:[
      {h:"Disputa estándar de no entrega",msg:"Hola, equipo de soporte de Instacart,\n\nEscribo para disputar una queja de no entrega en el batch #[BATCH ID] del [DATE].\n\nCompleté esta entrega con éxito. Mi evidencia:\n- Foto de entrega mostrando las bolsas en [ADDRESS]\n- Datos GPS confirmando que estuve en la ubicación de entrega a las [TIME]\n- Registro de confirmación de entrega en la app\n- Todos los artículos de este batch fueron escaneados y verificados\n\nSolicito:\n1. Que esta queja se revise contra mi foto de entrega y mis datos GPS\n2. Que se revierta cualquier impacto en mi calificación o posición como Shopper\n\nGracias.",w:"'Batch ID' es el término específico de Instacart. Incluir 'todos los artículos fueron escaneados' agrega un dato que los agentes pueden verificar contra el registro de escaneo — único de Instacart y una evidencia muy fuerte."},
    ]},
    {e:"📦",t:"Disputa por artículo faltante o equivocado",urgency:"ALTA — La queja más común en Instacart",color:"#F43F5E",secs:[
      {h:"El artículo estaba agotado — seguiste el protocolo",msg:"Hola, equipo de soporte de Instacart,\n\nDisputo una queja sobre un artículo faltante en el batch #[BATCH ID] del [DATE].\n\nEl artículo [ITEM NAME] no estaba disponible en [STORE NAME]. Lo manejé correctamente:\n- Marqué el artículo como agotado en la app de Instacart a las [TIME]\n- Seleccioné un reemplazo aprobado / dejé el artículo sin entregar según la preferencia del cliente\n- Escribí al cliente a través de la app antes de pagar\n\nMis acciones dentro de la app para este batch muestran que seguí el protocolo de agotados de Instacart al pie de la letra. Por favor revisen la actividad de mi batch y eliminen esta queja.\n\nGracias.",w:"El registro de actividad del batch de Instacart muestra cada acción que tomaste. Esta apelación dirige al agente a ese registro, lo cual es mucho más convincente que un relato verbal."},
    ]},
    {e:"🔄",t:"Escalación — Primera apelación negada",urgency:"USAR DESPUÉS DE UNA PRIMERA NEGACIÓN",color:"#8B5CF6",secs:[
      {h:"Solicitud de revisión senior",msg:"Hola,\n\nDoy seguimiento a una solicitud anterior al soporte de Instacart sobre el batch #[BATCH ID] del [DATE].\n\nMi primera apelación fue negada. Solicito escalación a un especialista senior de soporte para Shoppers porque:\n- Mi foto de entrega y mi registro de actividad del batch no fueron revisados por completo\n- La queja contradice mis acciones documentadas dentro de la app\n- Esto sigue afectando mi calificación como Shopper y mi acceso a batches\n\nHe sido un Shopper activo de Instacart desde el [DATE] con un historial sólido. Pido una revisión completa.\n\nGracias.",w:"Solicitar un 'especialista senior de soporte para Shoppers' con ese título mueve tu ticket más allá de los agentes de primer nivel que usan respuestas con guion."},
    ]},
  ],
  amazonflex:[
    {e:"🚫",t:"Falso 'nunca recibido' / paquete faltante",urgency:"ALTA — Afecta directamente tu posición",color:"#F43F5E",secs:[
      {h:"Apelación estándar por paquete faltante",msg:"Hola, equipo de soporte de Amazon Flex,\n\nApelo una queja por paquete faltante en el bloque [BLOCK ID] para el paquete TBA [TBA NUMBER] entregado el [DATE].\n\nEsta entrega se completó con éxito. Mi documentación:\n- Foto de entrega tomada a través de la app de Amazon Flex mostrando el paquete en la puerta del cliente\n- Datos GPS confirmando que estuve en la dirección de entrega a las [TIME]\n- Registro de confirmación de entrega en la app\n\nSolicito que esta queja se revise y se elimine de mi historial.\n\nGracias.",w:"Incluye siempre el ID del bloque + TBA. El soporte de Amazon puede obtener tus registros exactos de GPS y foto."},
      {h:"Bloque con varios paquetes y una queja",msg:"Hola, equipo de soporte de Amazon Flex,\n\nApelo una queja por paquete faltante en el bloque [BLOCK ID] para el TBA [TBA NUMBER].\n\nTodos los demás paquetes de este bloque se entregaron con éxito. Tengo:\n- Prueba con foto para esta parada\n- Confirmación GPS en la dirección\n\nEsto parece ser un reclamo falso aislado. Por favor eliminen la penalización de mi historial.\n\nGracias.",w:"Amazon a menudo elimina penalizaciones de un solo paquete cuando el resto del bloque está limpio."},
    ]},
    {e:"⭐",t:"Penalización injusta en tu historial / calificación",urgency:"MEDIA",color:"#F5A623",secs:[
      {h:"Se tomó foto pero igual hubo penalización",msg:"Hola,\n\nSolicito la eliminación de una penalización de entrega en el bloque [BLOCK ID], TBA [TBA NUMBER].\n\nSeguí todos los procedimientos y tomé una foto de entrega a través de la app. El GPS confirma que estuve en la dirección. Por favor revisen la foto adjunta y los datos GPS y eliminen esto de mi historial.\n\nGracias.",w:"Enfatiza que usaste la foto dentro de la app — esta es la evidencia más fuerte que acepta Amazon."},
    ]},
    {e:"🔄",t:"Escalación — Apelación negada",urgency:"USAR DESPUÉS DE LA PRIMERA NEGACIÓN",color:"#8B5CF6",secs:[
      {h:"Solicitar revisión senior",msg:"Hola,\n\nDoy seguimiento a una apelación anterior para el bloque [BLOCK ID] / TBA [TBA NUMBER].\n\nMi apelación inicial fue negada, pero mi foto de entrega y mis registros GPS muestran claramente que el paquete fue entregado. Solicito escalación a un especialista senior para una revisión completa.\n\nGracias.",w:"Pedir un 'especialista senior' a menudo logra que ojos nuevos revisen tu caso."},
    ]},
  ],
  lyft:[
    {e:"⭐",t:"Calificación baja injusta",urgency:"ALTA — Afecta el acceso a viajes y la prioridad",color:"#F43F5E",secs:[
      {h:"Calificación causada por factores fuera de tu control",timing:"Presenta después de que se publique la calificación y baje tu promedio — Lyft no puede eliminar una calificación antes de que aparezca",msg:"Hola, equipo de soporte de Lyft,\n\nSolicito la eliminación de una calificación baja en el viaje #[TRIP ID] del [DATE].\n\nEsta calificación no refleja mi servicio real. Parece haber sido causada por [traffic delay / GPS navigation error / long pickup wait], lo cual estuvo fuera de mi control como conductor.\n\nMi calificación general y mi historial de manejo muestran un servicio consistente y profesional. La política de Lyft permite revisar calificaciones causadas por factores externos. Por favor revisen y eliminen esta calificación.\n\nGracias.",w:"Incluye siempre el ID del viaje — los agentes no pueden buscar tu registro sin él. 'Fuera de mi control como conductor' es exactamente el enfoque que busca el equipo de revisión de Lyft al decidir si elimina una calificación."},
      {h:"Calificación causada por una queja falsa",msg:"Hola, equipo de soporte de Lyft,\n\nSolicito la revisión de una calificación baja y una queja en el viaje #[TRIP ID] del [DATE].\n\nLa queja dice [describe complaint briefly]. Esto no ocurrió. Esto fue lo que realmente pasó:\n[Relato breve y objetivo — dónde recogiste, ruta tomada, ubicación de destino, cómo se sintió el viaje]\n\nHe sido conductor de Lyft desde el [DATE] con un historial consistente. Esta queja es inexacta y está afectando mi posición injustamente. Pido una revisión de los datos GPS del viaje y la eliminación de esta calificación.\n\nGracias.",w:"Mantén tu relato breve y objetivo — sin emociones. Los agentes de Lyft revisan rutas GPS y marcas de tiempo, no narrativas. Una línea de tiempo objetiva y limpia es mucho más persuasiva que una explicación larga."},
    ]},
    {e:"🚨",t:"Reporte de mala conducta de un pasajero",urgency:"PRESENTA DE INMEDIATO — Protege tu historial de seguridad",color:"#F43F5E",secs:[
      {h:"Reportar acoso o comportamiento amenazante",timing:"Presenta el mismo día — los reportes de seguridad se priorizan cuando se presentan pronto",msg:"Hola, equipo de seguridad de Lyft,\n\nPresento un reporte de seguridad sobre un pasajero en el viaje #[TRIP ID] del [DATE].\n\nLo que pasó:\n[Describe claramente — qué se dijo o hizo, en qué momento del viaje ocurrió, cómo respondiste y dónde terminaste el viaje si aplica]\n\nSolicito:\n1. Que este incidente se documente en la cuenta del pasajero\n2. Una revisión de si este pasajero debe ser marcado para futuros viajes\n3. Confirmación de que este reporte no afectará negativamente mi posición\n\nGracias.",w:"Presenta esto el mismo día. Dirigirlo al 'equipo de seguridad de Lyft' lo envía a un departamento especializado. Los reportes de mala conducta de pasajeros quedan registrados permanentemente y Lyft los toma en serio — pero debes presentar pronto."},
    ]},
    {e:"❌",t:"Disputa de cancelación",urgency:"MEDIA — Protege tu tasa de cancelación",color:"#F5A623",secs:[
      {h:"Tarifa de cancelación no recibida — el pasajero no se presentó",timing:"Presenta dentro de 24 horas — los datos GPS de llegada son más claros justo después del viaje",msg:"Hola, equipo de soporte de Lyft,\n\nSolicito la revisión de una tarifa de cancelación no recibida en el viaje #[TRIP ID] del [DATE].\n\nLlegué al punto de recogida a las [TIME] y esperé el tiempo requerido antes de cancelar. El pasajero no apareció y no me escribió a través de la app.\n\nMi GPS confirma que estuve en [PICKUP ADDRESS] durante el periodo de espera requerido. Solicito que la tarifa de cancelación correspondiente se acredite a mi cuenta.\n\nGracias.",w:"Lyft puede verificar tu hora de llegada GPS y cuánto esperaste. La mayoría de las disputas de cancelación por no-show se resuelven a favor del conductor cuando tu GPS confirma que estuviste en el punto."},
    ]},
    {e:"🔄",t:"Escalación — Apelación negada",urgency:"USAR DESPUÉS DE LA PRIMERA NEGACIÓN",color:"#8B5CF6",secs:[
      {h:"Solicitar revisión senior de la cuenta",msg:"Hola,\n\nDoy seguimiento a una solicitud anterior al soporte de Lyft sobre el viaje #[TRIP ID] del [DATE].\n\nMi solicitud inicial no se resolvió. Pido escalación a un especialista senior de cuentas de conductores.\n\nEl problema original: [brief summary — one sentence]\n\nEsto sigue afectando mi calificación como conductor y mis ingresos. He sido conductor de Lyft desde el [DATE] con un historial sólido y pido una revisión completa y justa.\n\nGracias.",w:"'Especialista senior de cuentas de conductores' dirige tu ticket más allá del soporte de primer nivel. La mayoría de los conductores se rinden después de una primera negación — este solo seguimiento a menudo logra un resultado diferente."},
    ]},
  ],
  uber:[
    {e:"⭐",t:"Calificación injusta de un pasajero",urgency:"MEDIA — Afecta tu posición y el nivel Uber Pro",color:"#F5A623",secs:[
      {h:"Calificación causada por tráfico, navegación o precio",timing:"Presenta después de que se publique la calificación — Uber no puede eliminar una calificación que aún no aparece",msg:"Hola, equipo de soporte de Uber,\n\nSolicito la eliminación de una calificación baja en el viaje #[TRIP ID] del [DATE].\n\nPor el momento y cualquier comentario dejado, creo que el pasajero me calificó bajo por [traffic delay / navigation issue / trip price] — nada de lo cual está dentro de mi control como conductor.\n\nLa política de calificaciones de Uber excluye explícitamente calificaciones causadas por tráfico, navegación, precios y otros factores fuera del control del conductor. Pido que esta calificación se revise y se elimine bajo esa política.\n\nGracias.",w:"Las quejas por precio, la frustración por tráfico y los errores de navegación están explícitamente listados en la política de exclusión de calificaciones de Uber. Nombrar la categoría específica le da al agente un ancla clara de política para aprobar la eliminación."},
      {h:"Calificación de un pasajero que siempre califica bajo a los conductores",msg:"Hola, equipo de soporte de Uber,\n\nSolicito una revisión de una calificación baja recibida en el viaje #[TRIP ID] del [DATE].\n\nCompleté este viaje de forma profesional y segura. Solicito revisión porque creo que esta calificación puede no reflejar un problema genuino de servicio.\n\nLa política de Uber permite excluir calificaciones de pasajeros que consistentemente califican bajo a los conductores. Por favor revisen el historial de calificaciones de este pasajero y consideren la eliminación si el patrón aplica.\n\nMi calificación antes de esto era [X stars]. Gracias.",w:"El sistema de Uber ya excluye automáticamente algunas calificaciones bajas de quienes califican bajo con frecuencia. Esta carta acelera esa revisión al plantear la inquietud explícitamente. Mantenlo breve y objetivo."},
    ]},
    {e:"🚫",t:"Queja falsa de un pasajero",urgency:"ALTA — Puede afectar tu cuenta",color:"#F43F5E",secs:[
      {h:"Disputar una queja de un pasajero",timing:"Presenta dentro de 24 horas — Uber puede restringir cuentas temporalmente rápido después de quejas de seguridad",msg:"Hola, equipo de soporte de Uber,\n\nEscribo para disputar una queja presentada en mi contra en el viaje #[TRIP ID] del [DATE].\n\nCompleté este viaje de forma profesional y segura. La queja es inexacta. Esto es lo que puedo documentar:\n- El nombre del pasajero fue confirmado al recogerlo según la política de Uber\n- Los datos GPS confirman que se tomó la ruta correcta\n- No ocurrieron incidentes durante el viaje\n\nSolicito:\n1. Una revisión completa de esta queja contra mi registro del viaje y mis datos GPS\n2. Que se revierta cualquier impacto negativo en mi cuenta\n3. Una revisión del historial de quejas de este pasajero si esto es un patrón\n\nGracias.",w:"Empieza con tu documentación, no con tu negación. Los agentes revisan datos del viaje, no argumentos. Pedir una revisión del historial de quejas indica que entiendes el proceso formal — y que no te irás después de una sola respuesta."},
    ]},
    {e:"🔄",t:"Escalación — Primera apelación negada",urgency:"USAR DESPUÉS DE UNA PRIMERA NEGACIÓN",color:"#8B5CF6",secs:[
      {h:"Escalar a un especialista senior",msg:"Hola,\n\nDoy seguimiento a una solicitud anterior sobre el viaje de Uber #[TRIP ID] del [DATE].\n\nMi apelación inicial no se resolvió. Solicito escalación a un especialista senior de cuentas porque:\n- Mis datos GPS y mi registro del viaje no fueron revisados correctamente\n- La queja contradice mi historial documentado de viajes\n- Esto sigue afectando mi cuenta y mis ingresos\n\nHe sido conductor de Uber desde el [DATE] con un historial sólido. Pido una revisión exhaustiva.\n\nGracias.",w:"Pedir un 'especialista senior de cuentas' dirige tu ticket a una revisión de nivel superior. La mayoría de los conductores se agotan con agentes de primer nivel — esta solicitud de escalación a menudo logra un resultado significativamente diferente."},
    ]},
  ],
  gopuff:[
    {e:"🚫",t:"Queja falsa de no entrega",urgency:"ALTA — Puede afectar tu cuenta",color:"#F43F5E",secs:[
      {h:"Disputa estándar de no entrega",msg:"Hola, equipo de soporte de GoPuff,\n\nEscribo para disputar una queja de no entrega en el pedido #[ORDER ID] del [DATE].\n\nCompleté esta entrega con éxito. Mi documentación:\n- Foto de entrega tomada en [ADDRESS] mostrando los artículos en la puerta\n- Datos GPS confirmando mi ubicación en [ADDRESS] a las [TIME]\n- Confirmación de entrega dentro de la app\n\nSolicito:\n1. Que esta queja se revise contra mi foto y mis datos GPS\n2. Que se revierta cualquier impacto negativo en mi cuenta de conductor\n\nGracias.",w:"El soporte de GoPuff revisa la foto y los datos GPS igual que las otras plataformas. Empieza con tu evidencia — primero la foto, luego el GPS, luego la confirmación de la app. Mantenlo objetivo y breve."},
    ]},
    {e:"⛔",t:"Apelación de desactivación de cuenta",urgency:"ALTA — Envía lo antes posible",color:"#F43F5E",secs:[
      {h:"Apelación general de desactivación",timing:"Presenta en cuanto recibas el aviso de desactivación — los plazos de respuesta son cortos",msg:"Hola, equipo de soporte de GoPuff,\n\nEscribo para apelar la desactivación de mi cuenta de conductor de GoPuff, de la cual recibí aviso el [DATE].\n\nCreo que esta desactivación se hizo por error. Este es mi relato de la situación:\n- [Describe what happened, factually and briefly]\n- Siempre he seguido las Normas de la Comunidad de GoPuff sobre Seguridad, Respeto e Integridad\n- He completado [X] entregas en la plataforma con un historial limpio\n\nPido una revisión completa de mi historial de cuenta y del incidente específico citado. Estoy comprometido con los estándares de GoPuff y agradecería la oportunidad de continuar.\n\nGracias.",w:"Los motivos de desactivación declarados de GoPuff son violaciones de Seguridad, Respeto o Integridad. Enmarca tu apelación en torno a tu cumplimiento de esas tres categorías. Menciona tu cantidad de entregas — los conductores con un historial largo y limpio reciben más beneficio de la duda."},
      {h:"Desactivación causada por un error en la verificación de antecedentes de Checkr",msg:"Hola, equipo de soporte de GoPuff,\n\nApelo la desactivación de mi cuenta, que creo fue provocada por un error en mi verificación de antecedentes de Checkr.\n\nHe revisado mis resultados y creo que el siguiente punto es inexacto:\n- [Describe the specific item in dispute]\n\nHe presentado una disputa directamente con Checkr en consumer.checkr.com. Bajo el Fair Credit Reporting Act, tengo derecho a disputar información inexacta de mis antecedentes.\n\nPido a GoPuff que mantenga mi desactivación en espera mientras se resuelve mi disputa con Checkr. Puedo proporcionar documentación de mi disputa si la solicitan.\n\nGracias.",w:"Los errores en verificaciones de antecedentes vía Checkr son una de las causas más comunes de desactivación en GoPuff. Presenta primero la disputa con Checkr, luego haz referencia a ella en tu apelación a GoPuff. Esto crea un rastro documentado y le da a la plataforma una razón para esperar antes de hacer permanente la desactivación."},
    ]},
  ],
};

var PLATFORM_CHECKLISTS_ES = {
  doordash:[
    {e:"📸",t:"Foto de entrega tomada — puerta y bolsas visibles"},
    {e:"💬",t:"Mensaje al cliente a través de la app de DoorDash"},
    {e:"📍",t:"GPS activo durante toda la entrega"},
    {e:"📋",t:"Pedido marcado como entregado en la app"},
    {e:"🖼️",t:"Captura de pantalla de la confirmación de entrega"},
    {e:"📝",t:"Número de pedido anotado si algo se sintió raro"},
  ],
  ubereats:[
    {e:"📸",t:"Foto enviada a través de la app de Uber Eats"},
    {e:"💬",t:"Mensaje al cliente dentro de la app (no por SMS)"},
    {e:"📍",t:"GPS activo durante todo el viaje"},
    {e:"🆔",t:"Captura del ID del viaje si algo salió mal"},
    {e:"📋",t:"Entrega confirmada en la app de Uber Eats"},
    {e:"⏱️",t:"Espera larga en el restaurante documentada con un mensaje al cliente"},
  ],
  spark:[
    {e:"📸",t:"Foto de entrega tomada mostrando todas las bolsas en la puerta"},
    {e:"💬",t:"Mensaje al cliente vía app de Spark sobre cualquier cambio"},
    {e:"📍",t:"GPS activo durante todo el viaje"},
    {e:"📋",t:"Entrega confirmada en la app de Spark"},
    {e:"🛒",t:"Artículos agotados marcados en la app antes de pagar"},
    {e:"🧾",t:"Captura del resumen de entrega después de completarla"},
  ],
  instacart:[
    {e:"📸",t:"Foto de entrega enviada en la app de Instacart"},
    {e:"🛒",t:"Todos los artículos disponibles escaneados en la tienda"},
    {e:"💬",t:"Mensaje al cliente dentro de la app sobre cualquier sustitución"},
    {e:"📍",t:"GPS activo durante todo el batch"},
    {e:"📋",t:"Batch confirmado como completado en la app"},
    {e:"🧾",t:"Captura del resumen del batch después de la entrega"},
  ],  lyft:[
    {e:"🪪",t:"Nombre del pasajero confirmado antes de que subiera al auto"},
    {e:"📱",t:"GPS activo y teléfono montado antes de iniciar el viaje"},
    {e:"🚗",t:"Auto limpio y sin olores fuertes"},
    {e:"📋",t:"Captura del ID del viaje si algo se sintió raro durante el viaje"},
    {e:"⭐",t:"Pasajero calificado con 5 estrellas justo después de dejarlo"},
    {e:"🔇",t:"Deja que el pasajero marque el tono de la conversación — sin charla forzada"},
  ],
  amazonflex:[
    {e:"📸",t:"Foto de entrega tomada en la app de Flex"},
    {e:"📍",t:"GPS activo durante todo el bloque"},
    {e:"🔢",t:"Paquetes escaneados una dirección a la vez (bloques con varias paradas)"},
    {e:"🖼️",t:"Captura de la pantalla de confirmación de entrega"},
    {e:"📋",t:"ID del bloque y números TBA anotados si algo se sintió raro"},
    {e:"🔄",t:"Paquetes no entregables devueltos con el código de motivo correcto"},
  ],
  uber:[
    {e:"🪪",t:"Nombre del pasajero confirmado antes de que subiera al auto"},
    {e:"📱",t:"GPS activo y teléfono montado antes de iniciar el viaje"},
    {e:"🚗",t:"Auto limpio y sin olores fuertes"},
    {e:"📋",t:"Captura del ID del viaje si algo se sintió raro durante el viaje"},
    {e:"⭐",t:"Pasajero calificado con 5 estrellas justo después de dejarlo"},
    {e:"🔇",t:"Deja que el pasajero marque el tono de la conversación — sin charla forzada"},
  ],
  gopuff:[
    {e:"📦",t:"Cantidad de pedidos verificada en el centro antes de salir"},
    {e:"📸",t:"Foto de entrega tomada — artículos en la puerta con la dirección visible"},
    {e:"📍",t:"GPS activo durante toda la entrega"},
    {e:"💬",t:"Mensaje al cliente a través de la app de GoPuff si surgió algún problema"},
    {e:"📋",t:"ID del pedido anotado si algo se sintió raro durante la entrega"},
  ],
};

