// Precompiles app1.jsx + app2.jsx into a single minified app.bundle.js.
// Replaces the old in-browser Babel standalone transpile (which downloaded ~3MB
// and recompiled all JSX on every page load). The two sources share one global
// scope (same as the old eval-based loader), so each is transformed
// individually with esbuild and the outputs are concatenated.
//
// Run: npm run build   (Vercel runs this automatically on deploy)

import { readFileSync, writeFileSync } from "node:fs";
import { transformSync } from "esbuild";

const SOURCES = ["app1.jsx", "app2.jsx"];
const OUT = "app.bundle.js";

const parts = SOURCES.map((file) => {
  const code = readFileSync(file, "utf8");
  const out = transformSync(code, {
    loader: "jsx",
    jsx: "transform", // classic React.createElement (matches old Babel preset)
    minify: true,
    target: "es2019",
    sourcefile: file,
  });
  return `// ---- ${file} ----\n${out.code}`;
});

// Fail loudly if app.html still references the old in-browser Babel loader.
const html = readFileSync("app.html", "utf8");
if (html.includes("babel.min.js") || html.includes("text/babel")) {
  console.error(
    "ERROR: app.html still references in-browser Babel. " +
      "Remove the babel script tag and text/babel loader before building."
  );
  process.exit(1);
}

const banner = `/* DropPilot app bundle — generated by npm run build. Do not edit directly; edit app1.jsx / app2.jsx instead. */\n`;
writeFileSync(OUT, banner + parts.join("\n") + "\n");
console.log(`Wrote ${OUT} (${(banner.length + parts.join("\n").length).toLocaleString()} bytes)`);
