// Precompiles app1.jsx + app2.jsx into a single minified app.bundle.js and
// stages every static file into public/ for Vercel.
//
// Replaces the old in-browser Babel standalone transpile (which downloaded ~3MB
// and recompiled all JSX on every page load). The two sources share one global
// scope (same as the old eval-based loader), so each is transformed
// individually with esbuild and the outputs are concatenated.
//
// Vercel runs `npm run build` on deploy and serves static files from the
// output directory configured in vercel.json ("public"). api/ and
// middleware.js stay at the repo root — Vercel picks those up separately.
//
// Run: npm run build

import { readFileSync, writeFileSync, copyFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { transformSync } from "esbuild";

const SOURCES = ["app1.jsx", "app2.jsx"];
const OUT_DIR = "public";
const BUNDLE = "app.bundle.js";

// Static files served as-is alongside the bundle. (debug*.html diagnostics
// are intentionally excluded — they are slated for removal before merge.)
const STATIC = [
  "app.html",
  "index.html",
  "privacy.html",
  "terms.html",
  "robots.txt",
  ".nojekyll",
  "content-en1.js",
  "content-en2.js",
  "content-es1.js",
  "content-es2.js",
];

const parts = SOURCES.map((file) => {
  const code = readFileSync(file, "utf8");
  const out = transformSync(code, {
    loader: "jsx",
    jsx: "transform", // classic React.createElement (matches old Babel preset)
    minify: true,
    target: "es2019",
    sourcefile: file,
  });
  return `// ---- ${file} ----\n${out.code}`;
});

// Fail loudly if app.html still references the old in-browser Babel loader.
const html = readFileSync("app.html", "utf8");
if (html.includes("babel.min.js") || html.includes("text/babel")) {
  console.error(
    "ERROR: app.html still references in-browser Babel. " +
      "Remove the babel script tag and text/babel loader before building."
  );
  process.exit(1);
}

mkdirSync(OUT_DIR, { recursive: true });

const banner = `/* DropPilot app bundle — generated by npm run build. Do not edit directly; edit app1.jsx / app2.jsx instead. */\n`;
const bundlePath = join(OUT_DIR, BUNDLE);
writeFileSync(bundlePath, banner + parts.join("\n") + "\n");
console.log(
  `Wrote ${bundlePath} (${(banner.length + parts.join("\n").length).toLocaleString()} bytes)`
);

for (const file of STATIC) {
  const dest = join(OUT_DIR, file);
  mkdirSync(dirname(dest), { recursive: true });
  copyFileSync(file, dest);
  console.log(`Copied ${file} -> ${dest}`);
}
